<?php
#This file was last reorganized on 27th of September 2017 01:41:51 PM UTC

$text['title-network_cc']['en-us'] = "调度目的地";
$text['title-network_cc']['ar-eg'] = "Network CC";
$text['title-network_cc']['de-at'] = "Network CC";
$text['title-network_cc']['de-ch'] = "Network CC";
$text['title-network_cc']['de-de'] = "Network CC";
$text['title-network_cc']['es-cl'] = "Network CC";
$text['title-network_cc']['es-mx'] = "Network CC";
$text['title-network_cc']['fr-ca'] = "Network CC";
$text['title-network_cc']['fr-fr'] = "Network CC";
$text['title-network_cc']['he-il'] = "Network CC";
$text['title-network_cc']['it-it'] = "Network CC";
$text['title-network_cc']['nl-nl'] = "Network CC";
$text['title-network_cc']['pl-pl'] = "Network CC";
$text['title-network_cc']['pt-br'] = "Network CC";
$text['title-network_cc']['pt-pt'] = "Network CC";
$text['title-network_cc']['ro-ro'] = "Network CC";
$text['title-network_cc']['ru-ru'] = "Network CC";
$text['title-network_cc']['sv-se'] = "Network CC";
$text['title-network_cc']['uk-ua'] = "Network CC";

$text['label-network_name']['en-us'] = "调度目的地名称";
$text['label-network_name']['ar-eg'] = "Network CC Name";
$text['label-network_name']['de-at'] = "Network CC Name";
$text['label-network_name']['de-ch'] = "Network CC Name";
$text['label-network_name']['de-de'] = "Network CC Name";
$text['label-network_name']['es-cl'] = "Network CC Name";
$text['label-network_name']['es-mx'] = "Network CC Name";
$text['label-network_name']['fr-ca'] = "Network CC Name";
$text['label-network_name']['fr-fr'] = "Network CC Name";
$text['label-network_name']['he-il'] = "Network CC Name";
$text['label-network_name']['it-it'] = "Network CC Name";
$text['label-network_name']['nl-nl'] = "Network CC Name";
$text['label-network_name']['pl-pl'] = "Network CC Name";
$text['label-network_name']['pt-br'] = "Network CC Name";
$text['label-network_name']['pt-pt'] = "Network CC Name";
$text['label-network_name']['ro-ro'] = "Network CC Name";
$text['label-network_name']['ru-ru'] = "Network CC Name";
$text['label-network_name']['sv-se'] = "Network CC Name";
$text['label-network_name']['uk-ua'] = "Network CC Name";

$text['label-network_caller']['en-us'] = "对接号码";
$text['label-network_caller']['ar-eg'] = "Network Caller";
$text['label-network_caller']['de-at'] = "Network Caller";
$text['label-network_caller']['de-ch'] = "Network Caller";
$text['label-network_caller']['de-de'] = "Network Caller";
$text['label-network_caller']['es-cl'] = "Network Caller";
$text['label-network_caller']['es-mx'] = "Network Caller";
$text['label-network_caller']['fr-ca'] = "Network Caller";
$text['label-network_caller']['fr-fr'] = "Network Caller";
$text['label-network_caller']['he-il'] = "Network Caller";
$text['label-network_caller']['it-it'] = "Network Caller";
$text['label-network_caller']['nl-nl'] = "Network Caller";
$text['label-network_caller']['pl-pl'] = "Network Caller";
$text['label-network_caller']['pt-br'] = "Network Caller";
$text['label-network_caller']['pt-pt'] = "Network Caller";
$text['label-network_caller']['ro-ro'] = "Network Caller";
$text['label-network_caller']['ru-ru'] = "Network Caller";
$text['label-network_caller']['sv-se'] = "Network Caller";
$text['label-network_caller']['uk-ua'] = "Network Caller";

$text['label-network_address']['en-us'] = "对接地址";
$text['label-network_address']['ar-eg'] = "Network Address";
$text['label-network_address']['de-at'] = "Network Address";
$text['label-network_address']['de-ch'] = "Network Address";
$text['label-network_address']['de-de'] = "Network Address";
$text['label-network_address']['es-cl'] = "Network Address";
$text['label-network_address']['es-mx'] = "Network Address";
$text['label-network_address']['fr-ca'] = "Network Address";
$text['label-network_address']['fr-fr'] = "Network Address";
$text['label-network_address']['he-il'] = "Network Address";
$text['label-network_address']['it-it'] = "Network Address";
$text['label-network_address']['nl-nl'] = "Network Address";
$text['label-network_address']['pl-pl'] = "Network Address";
$text['label-network_address']['pt-br'] = "Network Address";
$text['label-network_address']['pt-pt'] = "Network Address";
$text['label-network_address']['ro-ro'] = "Network Address";
$text['label-network_address']['ru-ru'] = "Network Address";
$text['label-network_address']['sv-se'] = "Network Address";
$text['label-network_address']['uk-ua'] = "Network Address";

$text['label-network_update_time']['en-us'] = "更新时间";
$text['label-network_update_time']['ar-eg'] = "Update Time";
$text['label-network_update_time']['de-at'] = "Update Time";
$text['label-network_update_time']['de-ch'] = "Update Time";
$text['label-network_update_time']['de-de'] = "Update Time";
$text['label-network_update_time']['es-cl'] = "Update Time";
$text['label-network_update_time']['es-mx'] = "Update Time";
$text['label-network_update_time']['fr-ca'] = "Update Time";
$text['label-network_update_time']['fr-fr'] = "Update Time";
$text['label-network_update_time']['he-il'] = "Update Time";
$text['label-network_update_time']['it-it'] = "Update Time";
$text['label-network_update_time']['nl-nl'] = "Update Time";
$text['label-network_update_time']['pl-pl'] = "Update Time";
$text['label-network_update_time']['pt-br'] = "Update Time";
$text['label-network_update_time']['pt-pt'] = "Update Time";
$text['label-network_update_time']['ro-ro'] = "Update Time";
$text['label-network_update_time']['ru-ru'] = "Update Time";
$text['label-network_update_time']['sv-se'] = "Update Time";
$text['label-network_update_time']['uk-ua'] = "Update Time";

$text['label-network_enabled']['en-us'] = "启用";
$text['label-network_enabled']['ar-eg'] = "Enabled";
$text['label-network_enabled']['de-at'] = "Enabled";
$text['label-network_enabled']['de-ch'] = "Enabled";
$text['label-network_enabled']['de-de'] = "Enabled";
$text['label-network_enabled']['es-cl'] = "Enabled";
$text['label-network_enabled']['es-mx'] = "Enabled";
$text['label-network_enabled']['fr-ca'] = "Enabled";
$text['label-network_enabled']['fr-fr'] = "Enabled";
$text['label-network_enabled']['he-il'] = "Enabled";
$text['label-network_enabled']['it-it'] = "Enabled";
$text['label-network_enabled']['nl-nl'] = "Enabled";
$text['label-network_enabled']['pl-pl'] = "Enabled";
$text['label-network_enabled']['pt-br'] = "Enabled";
$text['label-network_enabled']['pt-pt'] = "Enabled";
$text['label-network_enabled']['ro-ro'] = "Enabled";
$text['label-network_enabled']['ru-ru'] = "Enabled";
$text['label-network_enabled']['sv-se'] = "Enabled";
$text['label-network_enabled']['uk-ua'] = "Enabled";

$text['label-network_description']['en-us'] = "备注";
$text['label-network_description']['ar-eg'] = "Description";
$text['label-network_description']['de-at'] = "Description";
$text['label-network_description']['de-ch'] = "Description";
$text['label-network_description']['de-de'] = "Description";
$text['label-network_description']['es-cl'] = "Description";
$text['label-network_description']['es-mx'] = "Description";
$text['label-network_description']['fr-ca'] = "Description";
$text['label-network_description']['fr-fr'] = "Description";
$text['label-network_description']['he-il'] = "Description";
$text['label-network_description']['it-it'] = "Description";
$text['label-network_description']['nl-nl'] = "Description";
$text['label-network_description']['pl-pl'] = "Description";
$text['label-network_description']['pt-br'] = "Description";
$text['label-network_description']['pt-pt'] = "Description";
$text['label-network_description']['ro-ro'] = "Description";
$text['label-network_description']['ru-ru'] = "Description";
$text['label-network_description']['sv-se'] = "Description";
$text['label-network_description']['uk-ua'] = "Description";

$text['header-network-cc-add']['en-us'] = "添加调度目的地";
$text['header-network-cc-add']['ar-eg'] = "Add Network CC";
$text['header-network-cc-add']['de-at'] = "Add Network CC";
$text['header-network-cc-add']['de-ch'] = "Add Network CC";
$text['header-network-cc-add']['de-de'] = "Add Network CC";
$text['header-network-cc-add']['es-cl'] = "Add Network CC";
$text['header-network-cc-add']['es-mx'] = "Add Network CC";
$text['header-network-cc-add']['fr-ca'] = "Add Network CC";
$text['header-network-cc-add']['fr-fr'] = "Add Network CC";
$text['header-network-cc-add']['he-il'] = "Add Network CC";
$text['header-network-cc-add']['it-it'] = "Add Network CC";
$text['header-network-cc-add']['nl-nl'] = "Add Network CC";
$text['header-network-cc-add']['pl-pl'] = "Add Network CC";
$text['header-network-cc-add']['pt-br'] = "Add Network CC";
$text['header-network-cc-add']['pt-pt'] = "Add Network CC";
$text['header-network-cc-add']['ro-ro'] = "Add Network CC";
$text['header-network-cc-add']['ru-ru'] = "Add Network CC";
$text['header-network-cc-add']['sv-se'] = "Add Network CC";
$text['header-network-cc-add']['uk-ua'] = "Add Network CC";

$text['header-network-cc-edit']['en-us'] = "编辑调度目的地";
$text['header-network-cc-edit']['ar-eg'] = "Edit Network CC";
$text['header-network-cc-edit']['de-at'] = "Edit Network CC";
$text['header-network-cc-edit']['de-ch'] = "Edit Network CC";
$text['header-network-cc-edit']['de-de'] = "Edit Network CC";
$text['header-network-cc-edit']['es-cl'] = "Edit Network CC";
$text['header-network-cc-edit']['es-mx'] = "Edit Network CC";
$text['header-network-cc-edit']['fr-ca'] = "Edit Network CC";
$text['header-network-cc-edit']['fr-fr'] = "Edit Network CC";
$text['header-network-cc-edit']['he-il'] = "Edit Network CC";
$text['header-network-cc-edit']['it-it'] = "Edit Network CC";
$text['header-network-cc-edit']['nl-nl'] = "Edit Network CC";
$text['header-network-cc-edit']['pl-pl'] = "Edit Network CC";
$text['header-network-cc-edit']['pt-br'] = "Edit Network CC";
$text['header-network-cc-edit']['pt-pt'] = "Edit Network CC";
$text['header-network-cc-edit']['ro-ro'] = "Edit Network CC";
$text['header-network-cc-edit']['ru-ru'] = "Edit Network CC";
$text['header-network-cc-edit']['sv-se'] = "Edit Network CC";
$text['header-network-cc-edit']['uk-ua'] = "Edit Network CC";

$text['description-landing-route']['en-us'] = "落地路由是根据呼入主叫号码的归属地路由到指定的归属地";
$text['description-landing-route']['ar-eg'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-at'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-ch'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-de'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['es-cl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['es-mx'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['fr-ca'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['fr-fr'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['he-il'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['it-it'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['nl-nl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pl-pl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pt-br'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pt-pt'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['ro-ro'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['ru-ru'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['sv-se'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['uk-ua'] = "The landing route is to route to the call to phone location";

$text['description-network_name']['en-us'] = "输入名称";
$text['description-network_name']['ar-eg'] = "";
$text['description-network_name']['de-at'] = "";
$text['description-network_name']['de-ch'] = "";
$text['description-network_name']['de-de'] = "";
$text['description-network_name']['es-cl'] = "";
$text['description-network_name']['es-mx'] = "";
$text['description-network_name']['fr-ca'] = "";
$text['description-network_name']['fr-fr'] = "";
$text['description-network_name']['he-il'] = "";
$text['description-network_name']['it-it'] = "";
$text['description-network_name']['nl-nl'] = "";
$text['description-network_name']['pl-pl'] = "";
$text['description-network_name']['pt-br'] = "";
$text['description-network_name']['pt-pt'] = "";
$text['description-network_name']['ro-ro'] = "";
$text['description-network_name']['ru-ru'] = "";
$text['description-network_name']['sv-se'] = "";
$text['description-network_name']['uk-ua'] = "";

$text['description-network_caller']['en-us'] = "输入网关对接号码";
$text['description-network_caller']['ar-eg'] = "";
$text['description-network_caller']['de-at'] = "";
$text['description-network_caller']['de-ch'] = "";
$text['description-network_caller']['de-de'] = "";
$text['description-network_caller']['es-cl'] = "";
$text['description-network_caller']['es-mx'] = "";
$text['description-network_caller']['fr-ca'] = "";
$text['description-network_caller']['fr-fr'] = "";
$text['description-network_caller']['he-il'] = "";
$text['description-network_caller']['it-it'] = "";
$text['description-network_caller']['nl-nl'] = "";
$text['description-network_caller']['pl-pl'] = "";
$text['description-network_caller']['pt-br'] = "";
$text['description-network_caller']['pt-pt'] = "";
$text['description-network_caller']['ro-ro'] = "";
$text['description-network_caller']['ru-ru'] = "";
$text['description-network_caller']['sv-se'] = "";
$text['description-network_caller']['uk-ua'] = "";

$text['description-network_address']['en-us'] = "输入对接地址，格式：IP:Port";
$text['description-network_address']['ar-eg'] = "";
$text['description-network_address']['de-at'] = "";
$text['description-network_address']['de-ch'] = "";
$text['description-network_address']['de-de'] = "";
$text['description-network_address']['es-cl'] = "";
$text['description-network_address']['es-mx'] = "";
$text['description-network_address']['fr-ca'] = "";
$text['description-network_address']['fr-fr'] = "";
$text['description-network_address']['he-il'] = "";
$text['description-network_address']['it-it'] = "";
$text['description-network_address']['nl-nl'] = "";
$text['description-network_address']['pl-pl'] = "";
$text['description-network_address']['pt-br'] = "";
$text['description-network_address']['pt-pt'] = "";
$text['description-network_address']['ro-ro'] = "";
$text['description-network_address']['ru-ru'] = "";
$text['description-network_address']['sv-se'] = "";
$text['description-network_address']['uk-ua'] = "";

$text['description-network_enabled']['en-us'] = "设置状态";
$text['description-network_enabled']['ar-eg'] = "Set the current status at here.";
$text['description-network_enabled']['de-at'] = "Set the current status at here."; //copied from de-de
$text['description-network_enabled']['de-ch'] = "Set the current status at here."; //copied from de-de
$text['description-network_enabled']['de-de'] = "Set the current status at here.";
$text['description-network_enabled']['es-cl'] = "Set the current status at here.";
$text['description-network_enabled']['es-mx'] = "Set the current status at here."; //copied from es-cl
$text['description-network_enabled']['fr-ca'] = "Set the current status at here."; //copied from fr-fr
$text['description-network_enabled']['fr-fr'] = "Set the current status at here.";
$text['description-network_enabled']['he-il'] = "Set the current status at here.";
$text['description-network_enabled']['it-it'] = "Set the current status at here.";
$text['description-network_enabled']['nl-nl'] = "Set the current status at here.";
$text['description-network_enabled']['pl-pl'] = "Set the current status at here.";
$text['description-network_enabled']['pt-br'] = "Set the current status at here.";
$text['description-network_enabled']['pt-pt'] = "Set the current status at here.";
$text['description-network_enabled']['ro-ro'] = "Set the current status at here.";
$text['description-network_enabled']['ru-ru'] = "Set the current status at here.";
$text['description-network_enabled']['sv-se'] = "Set the current status at here.";
$text['description-network_enabled']['uk-ua'] = "Set the current status at here.";

$text['label-network_enabled']['en-us'] = "启用";
$text['label-network_enabled']['ar-eg'] = "Enabled";
$text['label-network_enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-network_enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-network_enabled']['de-de'] = "Aktiviert";
$text['label-network_enabled']['es-cl'] = "Activado";
$text['label-network_enabled']['es-mx'] = "Activado"; //copied from es-cl
$text['label-network_enabled']['fr-ca'] = "Actif"; //copied from fr-fr
$text['label-network_enabled']['fr-fr'] = "Actif";
$text['label-network_enabled']['he-il'] = "מופעל";
$text['label-network_enabled']['it-it'] = "Abilitato";
$text['label-network_enabled']['nl-nl'] = "";
$text['label-network_enabled']['pl-pl'] = "Włączona";
$text['label-network_enabled']['pt-br'] = "Ativado";
$text['label-network_enabled']['pt-pt'] = "Activado";
$text['label-network_enabled']['ro-ro'] = "";
$text['label-network_enabled']['ru-ru'] = "Включено";
$text['label-network_enabled']['sv-se'] = "Aktiverad";
$text['label-network_enabled']['uk-ua'] = "Включено";

$text['label-network_description']['en-us'] = "备注";
$text['label-network_description']['ar-eg'] = "Description";
$text['label-network_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-network_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-network_description']['de-de'] = "Beschreibung";
$text['label-network_description']['es-cl'] = "Descripción";
$text['label-network_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-network_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-network_description']['fr-fr'] = "Description";
$text['label-network_description']['he-il'] = "תאור";
$text['label-network_description']['it-it'] = "Descrizione";
$text['label-network_description']['nl-nl'] = "";
$text['label-network_description']['pl-pl'] = "Opis";
$text['label-network_description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['label-network_description']['pt-pt'] = "Descrição";
$text['label-network_description']['ro-ro'] = "";
$text['label-network_description']['ru-ru'] = "Описание";
$text['label-network_description']['sv-se'] = "Beskrivning";
$text['label-network_description']['uk-ua'] = "Опис";

$text['description-network_description']['en-us'] = "输入备注";
$text['description-network_description']['ar-eg'] = "Enter a description for this destination (optional).";
$text['description-network_description']['de-at'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional)."; //copied from de-de
$text['description-network_description']['de-ch'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional)."; //copied from de-de
$text['description-network_description']['de-de'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional).";
$text['description-network_description']['es-cl'] = "Ingrese una descripción para este destino (opcional)";
$text['description-network_description']['es-mx'] = "Ingrese una descripción para este destino (opcional)"; //copied from es-cl
$text['description-network_description']['fr-ca'] = "Entrez une description pour cette destination (facultative)."; //copied from fr-fr
$text['description-network_description']['fr-fr'] = "Entrez une description pour cette destination (facultative).";
$text['description-network_description']['he-il'] = "";
$text['description-network_description']['it-it'] = "Inserire una descrizione per questa destinazione (opzionale).";
$text['description-network_description']['nl-nl'] = "";
$text['description-network_description']['pl-pl'] = "Wpisz opis tej destynacji (opcjonalne)";
$text['description-network_description']['pt-br'] = "Insira uma descrição para este destino (opcional)";
$text['description-network_description']['pt-pt'] = "Introduza uma descrição para este destino (opcional).";
$text['description-network_description']['ro-ro'] = "";
$text['description-network_description']['ru-ru'] = "Введите описание для этого места назначения (опционально).";
$text['description-network_description']['sv-se'] = "Ange en beskrivning för denna destination (frivillig).";
$text['description-network_description']['uk-ua'] = "Введіть опис для номера (не обов’язково)";


?>
