<?php
#This file was last reorganized on 27th of September 2017 01:41:51 PM UTC

$text['title-mobile_code']['en-us'] = "手机号归属地";
$text['title-mobile_code']['ar-eg'] = "Mobile Code";
$text['title-mobile_code']['de-at'] = "Mobile Code";
$text['title-mobile_code']['de-ch'] = "Mobile Code";
$text['title-mobile_code']['de-de'] = "Mobile Code";
$text['title-mobile_code']['es-cl'] = "Mobile Code";
$text['title-mobile_code']['es-mx'] = "Mobile Code";
$text['title-mobile_code']['fr-ca'] = "Mobile Code";
$text['title-mobile_code']['fr-fr'] = "Mobile Code";
$text['title-mobile_code']['he-il'] = "Mobile Code";
$text['title-mobile_code']['it-it'] = "Mobile Code";
$text['title-mobile_code']['nl-nl'] = "Mobile Code";
$text['title-mobile_code']['pl-pl'] = "Mobile Code";
$text['title-mobile_code']['pt-br'] = "Mobile Code";
$text['title-mobile_code']['pt-pt'] = "Mobile Code";
$text['title-mobile_code']['ro-ro'] = "Mobile Code";
$text['title-mobile_code']['ru-ru'] = "Mobile Code";
$text['title-mobile_code']['sv-se'] = "Mobile Code";
$text['title-mobile_code']['uk-ua'] = "Mobile Code";

$text['label-mobile_prefix']['en-us'] = "手机号前缀";
$text['label-mobile_prefix']['ar-eg'] = "Mobile Prefix";
$text['label-mobile_prefix']['de-at'] = "Mobile Prefix";
$text['label-mobile_prefix']['de-ch'] = "Mobile Prefix";
$text['label-mobile_prefix']['de-de'] = "Mobile Prefix";
$text['label-mobile_prefix']['es-cl'] = "Mobile Prefix";
$text['label-mobile_prefix']['es-mx'] = "Mobile Prefix";
$text['label-mobile_prefix']['fr-ca'] = "Mobile Prefix";
$text['label-mobile_prefix']['fr-fr'] = "Mobile Prefix";
$text['label-mobile_prefix']['he-il'] = "Mobile Prefix";
$text['label-mobile_prefix']['it-it'] = "Mobile Prefix";
$text['label-mobile_prefix']['nl-nl'] = "Mobile Prefix";
$text['label-mobile_prefix']['pl-pl'] = "Mobile Prefix";
$text['label-mobile_prefix']['pt-br'] = "Mobile Prefix";
$text['label-mobile_prefix']['pt-pt'] = "Mobile Prefix";
$text['label-mobile_prefix']['ro-ro'] = "Mobile Prefix";
$text['label-mobile_prefix']['ru-ru'] = "Mobile Prefix";
$text['label-mobile_prefix']['sv-se'] = "Mobile Prefix";
$text['label-mobile_prefix']['uk-ua'] = "Mobile Prefix";

$text['label-mobile_isp']['en-us'] = "运营商";
$text['label-mobile_isp']['ar-eg'] = "Mobile ISP";
$text['label-mobile_isp']['de-at'] = "Mobile ISP";
$text['label-mobile_isp']['de-ch'] = "Mobile ISP";
$text['label-mobile_isp']['de-de'] = "Mobile ISP";
$text['label-mobile_isp']['es-cl'] = "Mobile ISP";
$text['label-mobile_isp']['es-mx'] = "Mobile ISP";
$text['label-mobile_isp']['fr-ca'] = "Mobile ISP";
$text['label-mobile_isp']['fr-fr'] = "Mobile ISP";
$text['label-mobile_isp']['he-il'] = "Mobile ISP";
$text['label-mobile_isp']['it-it'] = "Mobile ISP";
$text['label-mobile_isp']['nl-nl'] = "Mobile ISP";
$text['label-mobile_isp']['pl-pl'] = "Mobile ISP";
$text['label-mobile_isp']['pt-br'] = "Mobile ISP";
$text['label-mobile_isp']['pt-pt'] = "Mobile ISP";
$text['label-mobile_isp']['ro-ro'] = "Mobile ISP";
$text['label-mobile_isp']['ru-ru'] = "Mobile ISP";
$text['label-mobile_isp']['sv-se'] = "Mobile ISP";
$text['label-mobile_isp']['uk-ua'] = "Mobile ISP";

$text['label-province']['en-us'] = "省份";
$text['label-province']['ar-eg'] = "Province";
$text['label-province']['de-at'] = "Province";
$text['label-province']['de-ch'] = "Province";
$text['label-province']['de-de'] = "Province";
$text['label-province']['es-cl'] = "Province";
$text['label-province']['es-mx'] = "Province";
$text['label-province']['fr-ca'] = "Province";
$text['label-province']['fr-fr'] = "Province";
$text['label-province']['he-il'] = "Province";
$text['label-province']['it-it'] = "Province";
$text['label-province']['nl-nl'] = "Province";
$text['label-province']['pl-pl'] = "Province";
$text['label-province']['pt-br'] = "Province";
$text['label-province']['pt-pt'] = "Province";
$text['label-province']['ro-ro'] = "Province";
$text['label-province']['ru-ru'] = "Province";
$text['label-province']['sv-se'] = "Province";
$text['label-province']['uk-ua'] = "Province";

$text['label-mobile_isp']['en-us'] = "运营商";
$text['label-mobile_isp']['ar-eg'] = "ISP";
$text['label-mobile_isp']['de-at'] = "ISP";
$text['label-mobile_isp']['de-ch'] = "ISP";
$text['label-mobile_isp']['de-de'] = "ISP";
$text['label-mobile_isp']['es-cl'] = "ISP";
$text['label-mobile_isp']['es-mx'] = "ISP";
$text['label-mobile_isp']['fr-ca'] = "ISP";
$text['label-mobile_isp']['fr-fr'] = "ISP";
$text['label-mobile_isp']['he-il'] = "ISP";
$text['label-mobile_isp']['it-it'] = "ISP";
$text['label-mobile_isp']['nl-nl'] = "ISP";
$text['label-mobile_isp']['pl-pl'] = "ISP";
$text['label-mobile_isp']['pt-br'] = "ISP";
$text['label-mobile_isp']['pt-pt'] = "ISP";
$text['label-mobile_isp']['ro-ro'] = "ISP";
$text['label-mobile_isp']['ru-ru'] = "ISP";
$text['label-mobile_isp']['sv-se'] = "ISP";
$text['label-mobile_isp']['uk-ua'] = "ISP";

$text['label-yi_dong']['en-us'] = "移动";
$text['label-yi_dong']['ar-eg'] = "Yi Dong";
$text['label-yi_dong']['de-at'] = "Yi Dong";
$text['label-yi_dong']['de-ch'] = "Yi Dong";
$text['label-yi_dong']['de-de'] = "Yi Dong";
$text['label-yi_dong']['es-cl'] = "Yi Dong";
$text['label-yi_dong']['es-mx'] = "Yi Dong";
$text['label-yi_dong']['fr-ca'] = "Yi Dong";
$text['label-yi_dong']['fr-fr'] = "Yi Dong";
$text['label-yi_dong']['he-il'] = "Yi Dong";
$text['label-yi_dong']['it-it'] = "Yi Dong";
$text['label-yi_dong']['nl-nl'] = "Yi Dong";
$text['label-yi_dong']['pl-pl'] = "Yi Dong";
$text['label-yi_dong']['pt-br'] = "Yi Dong";
$text['label-yi_dong']['pt-pt'] = "Yi Dong";
$text['label-yi_dong']['ro-ro'] = "Yi Dong";
$text['label-yi_dong']['ru-ru'] = "Yi Dong";
$text['label-yi_dong']['sv-se'] = "Yi Dong";
$text['label-yi_dong']['uk-ua'] = "Yi Dong";

$text['label-lian_tong']['en-us'] = "联通";
$text['label-lian_tong']['ar-eg'] = "Lian Tong";
$text['label-lian_tong']['de-at'] = "Lian Tong";
$text['label-lian_tong']['de-ch'] = "Lian Tong";
$text['label-lian_tong']['de-de'] = "Lian Tong";
$text['label-lian_tong']['es-cl'] = "Lian Tong";
$text['label-lian_tong']['es-mx'] = "Lian Tong";
$text['label-lian_tong']['fr-ca'] = "Lian Tong";
$text['label-lian_tong']['fr-fr'] = "Lian Tong";
$text['label-lian_tong']['he-il'] = "Lian Tong";
$text['label-lian_tong']['it-it'] = "Lian Tong";
$text['label-lian_tong']['nl-nl'] = "Lian Tong";
$text['label-lian_tong']['pl-pl'] = "Lian Tong";
$text['label-lian_tong']['pt-br'] = "Lian Tong";
$text['label-lian_tong']['pt-pt'] = "Lian Tong";
$text['label-lian_tong']['ro-ro'] = "Lian Tong";
$text['label-lian_tong']['ru-ru'] = "Lian Tong";
$text['label-lian_tong']['sv-se'] = "Lian Tong";
$text['label-lian_tong']['uk-ua'] = "Lian Tong";

$text['label-dian_xin']['en-us'] = "电信";
$text['label-dian_xin']['ar-eg'] = "Dian Xin";
$text['label-dian_xin']['de-at'] = "Dian Xin";
$text['label-dian_xin']['de-ch'] = "Dian Xin";
$text['label-dian_xin']['de-de'] = "Dian Xin";
$text['label-dian_xin']['es-cl'] = "Dian Xin";
$text['label-dian_xin']['es-mx'] = "Dian Xin";
$text['label-dian_xin']['fr-ca'] = "Dian Xin";
$text['label-dian_xin']['fr-fr'] = "Dian Xin";
$text['label-dian_xin']['he-il'] = "Dian Xin";
$text['label-dian_xin']['it-it'] = "Dian Xin";
$text['label-dian_xin']['nl-nl'] = "Dian Xin";
$text['label-dian_xin']['pl-pl'] = "Dian Xin";
$text['label-dian_xin']['pt-br'] = "Dian Xin";
$text['label-dian_xin']['pt-pt'] = "Dian Xin";
$text['label-dian_xin']['ro-ro'] = "Dian Xin";
$text['label-dian_xin']['ru-ru'] = "Dian Xin";
$text['label-dian_xin']['sv-se'] = "Dian Xin";
$text['label-dian_xin']['uk-ua'] = "Dian Xin";

$text['label-route_weekday']['en-us'] = "日期类型";
$text['label-route_weekday']['ar-eg'] = "Weekday";
$text['label-route_weekday']['de-at'] = "Weekday";
$text['label-route_weekday']['de-ch'] = "Weekday";
$text['label-route_weekday']['de-de'] = "Weekday";
$text['label-route_weekday']['es-cl'] = "Weekday";
$text['label-route_weekday']['es-mx'] = "Weekday";
$text['label-route_weekday']['fr-ca'] = "Weekday";
$text['label-route_weekday']['fr-fr'] = "Weekday";
$text['label-route_weekday']['he-il'] = "Weekday";
$text['label-route_weekday']['it-it'] = "Weekday";
$text['label-route_weekday']['nl-nl'] = "Weekday";
$text['label-route_weekday']['pl-pl'] = "Weekday";
$text['label-route_weekday']['pt-br'] = "Weekday";
$text['label-route_weekday']['pt-pt'] = "Weekday";
$text['label-route_weekday']['ro-ro'] = "Weekday";
$text['label-route_weekday']['ru-ru'] = "Weekday";
$text['label-route_weekday']['sv-se'] = "Weekday";
$text['label-route_weekday']['uk-ua'] = "Weekday";

$text['label-route_start_time']['en-us'] = "开始时间";
$text['label-route_start_time']['ar-eg'] = "Start Time";
$text['label-route_start_time']['de-at'] = "Start Time";
$text['label-route_start_time']['de-ch'] = "Start Time";
$text['label-route_start_time']['de-de'] = "Start Time";
$text['label-route_start_time']['es-cl'] = "Start Time";
$text['label-route_start_time']['es-mx'] = "Start Time";
$text['label-route_start_time']['fr-ca'] = "Start Time";
$text['label-route_start_time']['fr-fr'] = "Start Time";
$text['label-route_start_time']['he-il'] = "Start Time";
$text['label-route_start_time']['it-it'] = "Start Time";
$text['label-route_start_time']['nl-nl'] = "Start Time";
$text['label-route_start_time']['pl-pl'] = "Start Time";
$text['label-route_start_time']['pt-br'] = "Start Time";
$text['label-route_start_time']['pt-pt'] = "Start Time";
$text['label-route_start_time']['ro-ro'] = "Start Time";
$text['label-route_start_time']['ru-ru'] = "Start Time";
$text['label-route_start_time']['sv-se'] = "Start Time";
$text['label-route_start_time']['uk-ua'] = "Start Time";

$text['label-route_end_time']['en-us'] = "结束时间";
$text['label-route_end_time']['ar-eg'] = "End Time";
$text['label-route_end_time']['de-at'] = "End Time";
$text['label-route_end_time']['de-ch'] = "End Time";
$text['label-route_end_time']['de-de'] = "End Time";
$text['label-route_end_time']['es-cl'] = "End Time";
$text['label-route_end_time']['es-mx'] = "End Time";
$text['label-route_end_time']['fr-ca'] = "End Time";
$text['label-route_end_time']['fr-fr'] = "End Time";
$text['label-route_end_time']['he-il'] = "End Time";
$text['label-route_end_time']['it-it'] = "End Time";
$text['label-route_end_time']['nl-nl'] = "End Time";
$text['label-route_end_time']['pl-pl'] = "End Time";
$text['label-route_end_time']['pt-br'] = "End Time";
$text['label-route_end_time']['pt-pt'] = "End Time";
$text['label-route_end_time']['ro-ro'] = "End Time";
$text['label-route_end_time']['ru-ru'] = "End Time";
$text['label-route_end_time']['sv-se'] = "End Time";
$text['label-route_end_time']['uk-ua'] = "End Time";

$text['label-area_code']['en-us'] = "区域码";
$text['label-area_code']['ar-eg'] = "Area Code";
$text['label-area_code']['de-at'] = "Area Code";
$text['label-area_code']['de-ch'] = "Area Code";
$text['label-area_code']['de-de'] = "Area Code";
$text['label-area_code']['es-cl'] = "Area Code";
$text['label-area_code']['es-mx'] = "Area Code";
$text['label-area_code']['fr-ca'] = "Area Code";
$text['label-area_code']['fr-fr'] = "Area Code";
$text['label-area_code']['he-il'] = "Area Code";
$text['label-area_code']['it-it'] = "Area Code";
$text['label-area_code']['nl-nl'] = "Area Code";
$text['label-area_code']['pl-pl'] = "Area Code";
$text['label-area_code']['pt-br'] = "Area Code";
$text['label-area_code']['pt-pt'] = "Area Code";
$text['label-area_code']['ro-ro'] = "Area Code";
$text['label-area_code']['ru-ru'] = "Area Code";
$text['label-area_code']['sv-se'] = "Area Code";
$text['label-area_code']['uk-ua'] = "Area Code";

$text['label-network_description']['en-us'] = "备注";
$text['label-network_description']['ar-eg'] = "Description";
$text['label-network_description']['de-at'] = "Description";
$text['label-network_description']['de-ch'] = "Description";
$text['label-network_description']['de-de'] = "Description";
$text['label-network_description']['es-cl'] = "Description";
$text['label-network_description']['es-mx'] = "Description";
$text['label-network_description']['fr-ca'] = "Description";
$text['label-network_description']['fr-fr'] = "Description";
$text['label-network_description']['he-il'] = "Description";
$text['label-network_description']['it-it'] = "Description";
$text['label-network_description']['nl-nl'] = "Description";
$text['label-network_description']['pl-pl'] = "Description";
$text['label-network_description']['pt-br'] = "Description";
$text['label-network_description']['pt-pt'] = "Description";
$text['label-network_description']['ro-ro'] = "Description";
$text['label-network_description']['ru-ru'] = "Description";
$text['label-network_description']['sv-se'] = "Description";
$text['label-network_description']['uk-ua'] = "Description";

$text['label-route_cmd']['en-us'] = "命令";
$text['label-route_cmd']['ar-eg'] = "Cmd";
$text['label-route_cmd']['de-at'] = "Cmd";
$text['label-route_cmd']['de-ch'] = "Cmd";
$text['label-route_cmd']['de-de'] = "Cmd";
$text['label-route_cmd']['es-cl'] = "Cmd";
$text['label-route_cmd']['es-mx'] = "Cmd";
$text['label-route_cmd']['fr-ca'] = "Cmd";
$text['label-route_cmd']['fr-fr'] = "Cmd";
$text['label-route_cmd']['he-il'] = "Cmd";
$text['label-route_cmd']['it-it'] = "Cmd";
$text['label-route_cmd']['nl-nl'] = "Cmd";
$text['label-route_cmd']['pl-pl'] = "Cmd";
$text['label-route_cmd']['pt-br'] = "Cmd";
$text['label-route_cmd']['pt-pt'] = "Cmd";
$text['label-route_cmd']['ro-ro'] = "Cmd";
$text['label-route_cmd']['ru-ru'] = "Cmd";
$text['label-route_cmd']['sv-se'] = "Cmd";
$text['label-route_cmd']['uk-ua'] = "Cmd";

$text['label-route_order']['en-us'] = "优先级";
$text['label-route_order']['ar-eg'] = "Order";
$text['label-route_order']['de-at'] = "Order";
$text['label-route_order']['de-ch'] = "Order";
$text['label-route_order']['de-de'] = "Order";
$text['label-route_order']['es-cl'] = "Order";
$text['label-route_order']['es-mx'] = "Order";
$text['label-route_order']['fr-ca'] = "Order";
$text['label-route_order']['fr-fr'] = "Order";
$text['label-route_order']['he-il'] = "Order";
$text['label-route_order']['it-it'] = "Order";
$text['label-route_order']['nl-nl'] = "Order";
$text['label-route_order']['pl-pl'] = "Order";
$text['label-route_order']['pt-br'] = "Order";
$text['label-route_order']['pt-pt'] = "Order";
$text['label-route_order']['ro-ro'] = "Order";
$text['label-route_order']['ru-ru'] = "Order";
$text['label-route_order']['sv-se'] = "Order";
$text['label-route_order']['uk-ua'] = "Order";

$text['description-route_order']['en-us'] = "输入优先级，数值越小优先级越高，优先级数值需大于0";
$text['description-route_order']['ar-eg'] = "Order";
$text['description-route_order']['de-at'] = "Order";
$text['description-route_order']['de-ch'] = "Order";
$text['description-route_order']['de-de'] = "Order";
$text['description-route_order']['es-cl'] = "Order";
$text['description-route_order']['es-mx'] = "Order";
$text['description-route_order']['fr-ca'] = "Order";
$text['description-route_order']['fr-fr'] = "Order";
$text['description-route_order']['he-il'] = "Order";
$text['description-route_order']['it-it'] = "Order";
$text['description-route_order']['nl-nl'] = "Order";
$text['description-route_order']['pl-pl'] = "Order";
$text['description-route_order']['pt-br'] = "Order";
$text['description-route_order']['pt-pt'] = "Order";
$text['description-route_order']['ro-ro'] = "Order";
$text['description-route_order']['ru-ru'] = "Order";
$text['description-route_order']['sv-se'] = "Order";
$text['description-route_order']['uk-ua'] = "Order";

$text['header-mobile-code-add']['en-us'] = "添加手机号前缀";
$text['header-mobile-code-add']['ar-eg'] = "Add Mobile Code";
$text['header-mobile-code-add']['de-at'] = "Add Mobile Code";
$text['header-mobile-code-add']['de-ch'] = "Add Mobile Code";
$text['header-mobile-code-add']['de-de'] = "Add Mobile Code";
$text['header-mobile-code-add']['es-cl'] = "Add Mobile Code";
$text['header-mobile-code-add']['es-mx'] = "Add Mobile Code";
$text['header-mobile-code-add']['fr-ca'] = "Add Mobile Code";
$text['header-mobile-code-add']['fr-fr'] = "Add Mobile Code";
$text['header-mobile-code-add']['he-il'] = "Add Mobile Code";
$text['header-mobile-code-add']['it-it'] = "Add Mobile Code";
$text['header-mobile-code-add']['nl-nl'] = "Add Mobile Code";
$text['header-mobile-code-add']['pl-pl'] = "Add Mobile Code";
$text['header-mobile-code-add']['pt-br'] = "Add Mobile Code";
$text['header-mobile-code-add']['pt-pt'] = "Add Mobile Code";
$text['header-mobile-code-add']['ro-ro'] = "Add Mobile Code";
$text['header-mobile-code-add']['ru-ru'] = "Add Mobile Code";
$text['header-mobile-code-add']['sv-se'] = "Add Mobile Code";
$text['header-mobile-code-add']['uk-ua'] = "Add Mobile Code";

$text['header-mobile-code-edit']['en-us'] = "编辑手机号前缀";
$text['header-mobile-code-edit']['ar-eg'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['de-at'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['de-ch'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['de-de'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['es-cl'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['es-mx'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['fr-ca'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['fr-fr'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['he-il'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['it-it'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['nl-nl'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['pl-pl'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['pt-br'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['pt-pt'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['ro-ro'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['ru-ru'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['sv-se'] = "Edit Mobile Code";
$text['header-mobile-code-edit']['uk-ua'] = "Edit Mobile Code";

$text['description-landing-route']['en-us'] = "落地路由是根据呼入主叫号码的归属地路由到指定的归属地";
$text['description-landing-route']['ar-eg'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-at'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-ch'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['de-de'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['es-cl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['es-mx'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['fr-ca'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['fr-fr'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['he-il'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['it-it'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['nl-nl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pl-pl'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pt-br'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['pt-pt'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['ro-ro'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['ru-ru'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['sv-se'] = "The landing route is to route to the call to phone location";
$text['description-landing-route']['uk-ua'] = "The landing route is to route to the call to phone location";

$text['description-mobile_prefix']['en-us'] = "输入手机号前缀";
$text['description-mobile_prefix']['ar-eg'] = "";
$text['description-mobile_prefix']['de-at'] = "";
$text['description-mobile_prefix']['de-ch'] = "";
$text['description-mobile_prefix']['de-de'] = "";
$text['description-mobile_prefix']['es-cl'] = "";
$text['description-mobile_prefix']['es-mx'] = "";
$text['description-mobile_prefix']['fr-ca'] = "";
$text['description-mobile_prefix']['fr-fr'] = "";
$text['description-mobile_prefix']['he-il'] = "";
$text['description-mobile_prefix']['it-it'] = "";
$text['description-mobile_prefix']['nl-nl'] = "";
$text['description-mobile_prefix']['pl-pl'] = "";
$text['description-mobile_prefix']['pt-br'] = "";
$text['description-mobile_prefix']['pt-pt'] = "";
$text['description-mobile_prefix']['ro-ro'] = "";
$text['description-mobile_prefix']['ru-ru'] = "";
$text['description-mobile_prefix']['sv-se'] = "";
$text['description-mobile_prefix']['uk-ua'] = "";

$text['description-province']['en-us'] = "输入省份";
$text['description-province']['ar-eg'] = "";
$text['description-province']['de-at'] = "";
$text['description-province']['de-ch'] = "";
$text['description-province']['de-de'] = "";
$text['description-province']['es-cl'] = "";
$text['description-province']['es-mx'] = "";
$text['description-province']['fr-ca'] = "";
$text['description-province']['fr-fr'] = "";
$text['description-province']['he-il'] = "";
$text['description-province']['it-it'] = "";
$text['description-province']['nl-nl'] = "";
$text['description-province']['pl-pl'] = "";
$text['description-province']['pt-br'] = "";
$text['description-province']['pt-pt'] = "";
$text['description-province']['ro-ro'] = "";
$text['description-province']['ru-ru'] = "";
$text['description-province']['sv-se'] = "";
$text['description-province']['uk-ua'] = "";

$text['description-city']['en-us'] = "输入城市";
$text['description-city']['ar-eg'] = "";
$text['description-city']['de-at'] = "";
$text['description-city']['de-ch'] = "";
$text['description-city']['de-de'] = "";
$text['description-city']['es-cl'] = "";
$text['description-city']['es-mx'] = "";
$text['description-city']['fr-ca'] = "";
$text['description-city']['fr-fr'] = "";
$text['description-city']['he-il'] = "";
$text['description-city']['it-it'] = "";
$text['description-city']['nl-nl'] = "";
$text['description-city']['pl-pl'] = "";
$text['description-city']['pt-br'] = "";
$text['description-city']['pt-pt'] = "";
$text['description-city']['ro-ro'] = "";
$text['description-city']['ru-ru'] = "";
$text['description-city']['sv-se'] = "";
$text['description-city']['uk-ua'] = "";

$text['description-route_telephone']['en-us'] = "输入组号码，多个号码之间以英文逗号分隔";
$text['description-route_telephone']['ar-eg'] = "";
$text['description-route_telephone']['de-at'] = "";
$text['description-route_telephone']['de-ch'] = "";
$text['description-route_telephone']['de-de'] = "";
$text['description-route_telephone']['es-cl'] = "";
$text['description-route_telephone']['es-mx'] = "";
$text['description-route_telephone']['fr-ca'] = "";
$text['description-route_telephone']['fr-fr'] = "";
$text['description-route_telephone']['he-il'] = "";
$text['description-route_telephone']['it-it'] = "";
$text['description-route_telephone']['nl-nl'] = "";
$text['description-route_telephone']['pl-pl'] = "";
$text['description-route_telephone']['pt-br'] = "";
$text['description-route_telephone']['pt-pt'] = "";
$text['description-route_telephone']['ro-ro'] = "";
$text['description-route_telephone']['ru-ru'] = "";
$text['description-route_telephone']['sv-se'] = "";
$text['description-route_telephone']['uk-ua'] = "";

$text['description-route_start_time']['en-us'] = "开始时间，默认为：00:00";
$text['description-route_start_time']['ar-eg'] = "";
$text['description-route_start_time']['de-at'] = "";
$text['description-route_start_time']['de-ch'] = "";
$text['description-route_start_time']['de-de'] = "";
$text['description-route_start_time']['es-cl'] = "";
$text['description-route_start_time']['es-mx'] = "";
$text['description-route_start_time']['fr-ca'] = "";
$text['description-route_start_time']['fr-fr'] = "";
$text['description-route_start_time']['he-il'] = "";
$text['description-route_start_time']['it-it'] = "";
$text['description-route_start_time']['nl-nl'] = "";
$text['description-route_start_time']['pl-pl'] = "";
$text['description-route_start_time']['pt-br'] = "";
$text['description-route_start_time']['pt-pt'] = "";
$text['description-route_start_time']['ro-ro'] = "";
$text['description-route_start_time']['ru-ru'] = "";
$text['description-route_start_time']['sv-se'] = "";
$text['description-route_start_time']['uk-ua'] = "";

$text['description-route_end_time']['en-us'] = "结束时间，默认为：23:59";
$text['description-route_end_time']['ar-eg'] = "";
$text['description-route_end_time']['de-at'] = "";
$text['description-route_end_time']['de-ch'] = "";
$text['description-route_end_time']['de-de'] = "";
$text['description-route_end_time']['es-cl'] = "";
$text['description-route_end_time']['es-mx'] = "";
$text['description-route_end_time']['fr-ca'] = "";
$text['description-route_end_time']['fr-fr'] = "";
$text['description-route_end_time']['he-il'] = "";
$text['description-route_end_time']['it-it'] = "";
$text['description-route_end_time']['nl-nl'] = "";
$text['description-route_end_time']['pl-pl'] = "";
$text['description-route_end_time']['pt-br'] = "";
$text['description-route_end_time']['pt-pt'] = "";
$text['description-route_end_time']['ro-ro'] = "";
$text['description-route_end_time']['ru-ru'] = "";
$text['description-route_end_time']['sv-se'] = "";
$text['description-route_end_time']['uk-ua'] = "";

$text['description-route_cmd']['en-us'] = "输入转发命令";
$text['description-route_cmd']['ar-eg'] = "";
$text['description-route_cmd']['de-at'] = "";
$text['description-route_cmd']['de-ch'] = "";
$text['description-route_cmd']['de-de'] = "";
$text['description-route_cmd']['es-cl'] = "";
$text['description-route_cmd']['es-mx'] = "";
$text['description-route_cmd']['fr-ca'] = "";
$text['description-route_cmd']['fr-fr'] = "";
$text['description-route_cmd']['he-il'] = "";
$text['description-route_cmd']['it-it'] = "";
$text['description-route_cmd']['nl-nl'] = "";
$text['description-route_cmd']['pl-pl'] = "";
$text['description-route_cmd']['pt-br'] = "";
$text['description-route_cmd']['pt-pt'] = "";
$text['description-route_cmd']['ro-ro'] = "";
$text['description-route_cmd']['ru-ru'] = "";
$text['description-route_cmd']['sv-se'] = "";
$text['description-route_cmd']['uk-ua'] = "";

$text['description-mobile_isp']['en-us'] = "选择运营商";
$text['description-mobile_isp']['ar-eg'] = "Select Mobile ISP";
$text['description-mobile_isp']['de-at'] = "Select Mobile ISP"; //copied from de-de
$text['description-mobile_isp']['de-ch'] = "Select Mobile ISP"; //copied from de-de
$text['description-mobile_isp']['de-de'] = "Select Mobile ISP";
$text['description-mobile_isp']['es-cl'] = "Select Mobile ISP";
$text['description-mobile_isp']['es-mx'] = "Select Mobile ISP"; //copied from es-cl
$text['description-mobile_isp']['fr-ca'] = "Select Mobile ISP"; //copied from fr-fr
$text['description-mobile_isp']['fr-fr'] = "Select Mobile ISP";
$text['description-mobile_isp']['he-il'] = "Select Mobile ISP";
$text['description-mobile_isp']['it-it'] = "Select Mobile ISP";
$text['description-mobile_isp']['nl-nl'] = "Select Mobile ISP";
$text['description-mobile_isp']['pl-pl'] = "Select Mobile ISP";
$text['description-mobile_isp']['pt-br'] = "Select Mobile ISP"; //copied from pt-pt
$text['description-mobile_isp']['pt-pt'] = "Select Mobile ISP";
$text['description-mobile_isp']['ro-ro'] = "Select Mobile ISP";
$text['description-mobile_isp']['ru-ru'] = "Select Mobile ISP";
$text['description-mobile_isp']['sv-se'] = "Select Mobile ISP";
$text['description-mobile_isp']['uk-ua'] = "Select Mobile ISP";

$text['description-network_enabled']['en-us'] = "设置状态";
$text['description-network_enabled']['ar-eg'] = "Set the current status at here.";
$text['description-network_enabled']['de-at'] = "Set the current status at here."; //copied from de-de
$text['description-network_enabled']['de-ch'] = "Set the current status at here."; //copied from de-de
$text['description-network_enabled']['de-de'] = "Set the current status at here.";
$text['description-network_enabled']['es-cl'] = "Set the current status at here.";
$text['description-network_enabled']['es-mx'] = "Set the current status at here."; //copied from es-cl
$text['description-network_enabled']['fr-ca'] = "Set the current status at here."; //copied from fr-fr
$text['description-network_enabled']['fr-fr'] = "Set the current status at here.";
$text['description-network_enabled']['he-il'] = "Set the current status at here.";
$text['description-network_enabled']['it-it'] = "Set the current status at here.";
$text['description-network_enabled']['nl-nl'] = "Set the current status at here.";
$text['description-network_enabled']['pl-pl'] = "Set the current status at here.";
$text['description-network_enabled']['pt-br'] = "Set the current status at here.";
$text['description-network_enabled']['pt-pt'] = "Set the current status at here.";
$text['description-network_enabled']['ro-ro'] = "Set the current status at here.";
$text['description-network_enabled']['ru-ru'] = "Set the current status at here.";
$text['description-network_enabled']['sv-se'] = "Set the current status at here.";
$text['description-network_enabled']['uk-ua'] = "Set the current status at here.";

// ---------------------------------------------------------------------------------------------------------------------------

$text['title-destination-edit']['en-us'] = "目的地";
$text['title-destination-edit']['ar-eg'] = "Destination";
$text['title-destination-edit']['de-at'] = "Ziel"; //copied from de-de
$text['title-destination-edit']['de-ch'] = "Ziel"; //copied from de-de
$text['title-destination-edit']['de-de'] = "Ziel";
$text['title-destination-edit']['es-cl'] = "Editar Destino";
$text['title-destination-edit']['es-mx'] = "Editar Destino"; //copied from es-cl
$text['title-destination-edit']['fr-ca'] = "Editer la Destination"; //copied from fr-fr
$text['title-destination-edit']['fr-fr'] = "Editer la Destination";
$text['title-destination-edit']['he-il'] = "יעד";
$text['title-destination-edit']['it-it'] = "Destinazione";
$text['title-destination-edit']['nl-nl'] = "";
$text['title-destination-edit']['pl-pl'] = "Destynacja";
$text['title-destination-edit']['pt-br'] = "Editar destino";
$text['title-destination-edit']['pt-pt'] = "Editar Desvio";
$text['title-destination-edit']['ro-ro'] = "Destinație";
$text['title-destination-edit']['ru-ru'] = "Направление";
$text['title-destination-edit']['sv-se'] = "Destination";
$text['title-destination-edit']['uk-ua'] = "Номер";

$text['title-destination-add']['en-us'] = "目的地";
$text['title-destination-add']['ar-eg'] = "Destination";
$text['title-destination-add']['de-at'] = "Ziel"; //copied from de-de
$text['title-destination-add']['de-ch'] = "Ziel"; //copied from de-de
$text['title-destination-add']['de-de'] = "Ziel";
$text['title-destination-add']['es-cl'] = "Agregar Destino";
$text['title-destination-add']['es-mx'] = "Agregar Destino"; //copied from es-cl
$text['title-destination-add']['fr-ca'] = "Ajouter une Destination"; //copied from fr-fr
$text['title-destination-add']['fr-fr'] = "Ajouter une Destination";
$text['title-destination-add']['he-il'] = "יעד";
$text['title-destination-add']['it-it'] = "Destinazione";
$text['title-destination-add']['nl-nl'] = "";
$text['title-destination-add']['pl-pl'] = "Destynacja";
$text['title-destination-add']['pt-br'] = "Adicionar destino";
$text['title-destination-add']['pt-pt'] = "Adicionar Desvio";
$text['title-destination-add']['ro-ro'] = "Destinație";
$text['title-destination-add']['ru-ru'] = "Направление";
$text['title-destination-add']['sv-se'] = "Destination";
$text['title-destination-add']['uk-ua'] = "Номер";

$text['button-outbound']['en-us'] = "呼出";
$text['button-outbound']['ar-eg'] = "Outbound";
$text['button-outbound']['de-at'] = "Ausgehend"; //copied from de-de
$text['button-outbound']['de-ch'] = "Ausgehend"; //copied from de-de
$text['button-outbound']['de-de'] = "Ausgehend";
$text['button-outbound']['es-cl'] = "Saliente";
$text['button-outbound']['es-mx'] = "Saliente"; //copied from es-cl
$text['button-outbound']['fr-ca'] = "Sortant"; //copied from fr-fr
$text['button-outbound']['fr-fr'] = "Sortant";
$text['button-outbound']['he-il'] = "יוצא";
$text['button-outbound']['it-it'] = "In Uscita";
$text['button-outbound']['nl-nl'] = "";
$text['button-outbound']['pl-pl'] = "Wychodzący";
$text['button-outbound']['pt-br'] = "Saída"; //copied from pt-pt
$text['button-outbound']['pt-pt'] = "Saída";
$text['button-outbound']['ro-ro'] = "";
$text['button-outbound']['ru-ru'] = "Исходящий";
$text['button-outbound']['sv-se'] = "Utgående";
$text['button-outbound']['uk-ua'] = "Вихідний";

$text['button-inbound']['en-us'] = "呼入";
$text['button-inbound']['ar-eg'] = "Inbound";
$text['button-inbound']['de-at'] = "Eingehend"; //copied from de-de
$text['button-inbound']['de-ch'] = "Eingehend"; //copied from de-de
$text['button-inbound']['de-de'] = "Eingehend";
$text['button-inbound']['es-cl'] = "Entrante";
$text['button-inbound']['es-mx'] = "Entrante"; //copied from es-cl
$text['button-inbound']['fr-ca'] = "Entrant"; //copied from fr-fr
$text['button-inbound']['fr-fr'] = "Entrant";
$text['button-inbound']['he-il'] = "נכנס";
$text['button-inbound']['it-it'] = "In Entrata";
$text['button-inbound']['nl-nl'] = "";
$text['button-inbound']['pl-pl'] = "Przychodzący";
$text['button-inbound']['pt-br'] = "Entrada"; //copied from pt-pt
$text['button-inbound']['pt-pt'] = "Entrada";
$text['button-inbound']['ro-ro'] = "";
$text['button-inbound']['ru-ru'] = "Входящий";
$text['button-inbound']['sv-se'] = "Inkommande";
$text['button-inbound']['uk-ua'] = "Вхідний";

$text['select-global']['en-us'] = "Global";
$text['select-global']['ar-eg'] = "";
$text['select-global']['de-at'] = "Global"; //copied from de-de
$text['select-global']['de-ch'] = "Global"; //copied from de-de
$text['select-global']['de-de'] = "Global";
$text['select-global']['es-cl'] = "Global";
$text['select-global']['es-mx'] = "Global"; //copied from es-cl
$text['select-global']['fr-ca'] = "Mondial"; //copied from fr-fr
$text['select-global']['fr-fr'] = "Mondial";
$text['select-global']['he-il'] = "כללי";
$text['select-global']['it-it'] = "Globale";
$text['select-global']['nl-nl'] = "";
$text['select-global']['pl-pl'] = "Globalny";
$text['select-global']['pt-br'] = "Global"; //copied from pt-pt
$text['select-global']['pt-pt'] = "Global";
$text['select-global']['ro-ro'] = "Global";
$text['select-global']['ru-ru'] = "Глобальный";
$text['select-global']['sv-se'] = "Global";
$text['select-global']['uk-ua'] = "Глобальний";

$text['option-type_outbound']['en-us'] = "Outbound";
$text['option-type_outbound']['ar-eg'] = "صادر";
$text['option-type_outbound']['de-at'] = "Ausgehend"; //copied from de-de
$text['option-type_outbound']['de-ch'] = "Ausgehend"; //copied from de-de
$text['option-type_outbound']['de-de'] = "Ausgehend";
$text['option-type_outbound']['es-cl'] = "Saliente";
$text['option-type_outbound']['es-mx'] = "Saliente"; //copied from es-cl
$text['option-type_outbound']['fr-ca'] = "Sortant"; //copied from fr-fr
$text['option-type_outbound']['fr-fr'] = "Sortant";
$text['option-type_outbound']['he-il'] = "יוצא";
$text['option-type_outbound']['it-it'] = "In Uscita";
$text['option-type_outbound']['nl-nl'] = "";
$text['option-type_outbound']['pl-pl'] = "Wychodzący";
$text['option-type_outbound']['pt-br'] = "Saída"; //copied from pt-pt
$text['option-type_outbound']['pt-pt'] = "Saída";
$text['option-type_outbound']['ro-ro'] = "";
$text['option-type_outbound']['ru-ru'] = "Исходящий";
$text['option-type_outbound']['sv-se'] = "Utgående";
$text['option-type_outbound']['uk-ua'] = "Вихідний";

$text['option-type_inbound']['en-us'] = "Inbound";
$text['option-type_inbound']['ar-eg'] = "وارد";
$text['option-type_inbound']['de-at'] = "Eingehend"; //copied from de-de
$text['option-type_inbound']['de-ch'] = "Eingehend"; //copied from de-de
$text['option-type_inbound']['de-de'] = "Eingehend";
$text['option-type_inbound']['es-cl'] = "Entrante";
$text['option-type_inbound']['es-mx'] = "Entrante"; //copied from es-cl
$text['option-type_inbound']['fr-ca'] = "Entrant"; //copied from fr-fr
$text['option-type_inbound']['fr-fr'] = "Entrant";
$text['option-type_inbound']['he-il'] = "נכנס";
$text['option-type_inbound']['it-it'] = "In Ingresso";
$text['option-type_inbound']['nl-nl'] = "";
$text['option-type_inbound']['pl-pl'] = "Przychodzący";
$text['option-type_inbound']['pt-br'] = "Entrada"; //copied from pt-pt
$text['option-type_inbound']['pt-pt'] = "Entrada";
$text['option-type_inbound']['ro-ro'] = "";
$text['option-type_inbound']['ru-ru'] = "Входящий";
$text['option-type_inbound']['sv-se'] = "Inkommande";
$text['option-type_inbound']['uk-ua'] = "Вхідний";

$text['message-maximum_destinations']['en-us'] = "Maximum Destinations:";
$text['message-maximum_destinations']['ar-eg'] = "الحد الأقصي لجهات الأتصال";
$text['message-maximum_destinations']['de-at'] = "Maximale Anzahl an Ziele:"; //copied from de-de
$text['message-maximum_destinations']['de-ch'] = "Maximale Anzahl an Ziele:"; //copied from de-de
$text['message-maximum_destinations']['de-de'] = "Maximale Anzahl an Ziele:";
$text['message-maximum_destinations']['es-cl'] = "Destinos Máximo Permitido:";
$text['message-maximum_destinations']['es-mx'] = "Destinos Máximo Permitido:"; //copied from es-cl
$text['message-maximum_destinations']['fr-ca'] = "Destinations Maximum Autorisé:"; //copied from fr-fr
$text['message-maximum_destinations']['fr-fr'] = "Destinations Maximum Autorisé:";
$text['message-maximum_destinations']['he-il'] = "מקסימיום יעדים";
$text['message-maximum_destinations']['it-it'] = "Destinazioni Massime:";
$text['message-maximum_destinations']['nl-nl'] = "";
$text['message-maximum_destinations']['pl-pl'] = "Maksymalna ilość destynacji";
$text['message-maximum_destinations']['pt-br'] = "Destino máximo permitido";
$text['message-maximum_destinations']['pt-pt'] = "Destinos Máximo Permitido:";
$text['message-maximum_destinations']['ro-ro'] = "";
$text['message-maximum_destinations']['ru-ru'] = "Максимальное количество направлений:";
$text['message-maximum_destinations']['sv-se'] = "Max Antal Destinationer";
$text['message-maximum_destinations']['uk-ua'] = "Максимум номерів:";

$text['message-duplicate']['en-us'] = "Duplicate detected";
$text['message-duplicate']['ar-eg'] = "";
$text['message-duplicate']['de-at'] = "Bereits vorhanden"; //copied from de-de
$text['message-duplicate']['de-ch'] = "Bereits vorhanden"; //copied from de-de
$text['message-duplicate']['de-de'] = "Bereits vorhanden";
$text['message-duplicate']['es-cl'] = "Duplicar detectado";
$text['message-duplicate']['es-mx'] = "Duplicar detectado"; //copied from es-cl
$text['message-duplicate']['fr-ca'] = "Dupliquer détecté"; //copied from fr-fr
$text['message-duplicate']['fr-fr'] = "Dupliquer détecté";
$text['message-duplicate']['he-il'] = "זוהתה כפילות";
$text['message-duplicate']['it-it'] = "Rilevato Duplicato";
$text['message-duplicate']['nl-nl'] = "";
$text['message-duplicate']['pl-pl'] = "Wykryto duplikat";
$text['message-duplicate']['pt-br'] = "Detectado uma dubplicidade";
$text['message-duplicate']['pt-pt'] = "Duplicar detectado";
$text['message-duplicate']['ro-ro'] = "";
$text['message-duplicate']['ru-ru'] = "Обнаружено дублирование";
$text['message-duplicate']['sv-se'] = "Dubblett Upptäckt";
$text['message-duplicate']['uk-ua'] = "Знайдено дублікат";

$text['label-monthly_price_buy']['en-us'] = "Monthly buy price";
$text['label-monthly_price_buy']['ar-eg'] = "";
$text['label-monthly_price_buy']['de-at'] = "Monatlicher Einkaufspreis"; //copied from de-de
$text['label-monthly_price_buy']['de-ch'] = "Monatlicher Einkaufspreis"; //copied from de-de
$text['label-monthly_price_buy']['de-de'] = "Monatlicher Einkaufspreis";
$text['label-monthly_price_buy']['es-cl'] = "Precio mensual de compra";
$text['label-monthly_price_buy']['es-mx'] = "Precio mensual de compra"; //copied from es-cl
$text['label-monthly_price_buy']['fr-ca'] = "Prix mensuel d'achat"; //copied from fr-fr
$text['label-monthly_price_buy']['fr-fr'] = "Prix mensuel d'achat";
$text['label-monthly_price_buy']['he-il'] = "קנייה חודשית";
$text['label-monthly_price_buy']['it-it'] = "Prezzo acquisto mensile";
$text['label-monthly_price_buy']['nl-nl'] = "";
$text['label-monthly_price_buy']['pl-pl'] = "Miesięczna cena zakupu";
$text['label-monthly_price_buy']['pt-br'] = "Preço mensal de compra";
$text['label-monthly_price_buy']['pt-pt'] = "Preço mensal compra";
$text['label-monthly_price_buy']['ro-ro'] = "";
$text['label-monthly_price_buy']['ru-ru'] = "Месячный тариф покупки";
$text['label-monthly_price_buy']['sv-se'] = "Inköpspris / Månad";
$text['label-monthly_price_buy']['uk-ua'] = "Щомісячна ціна купівлі";

$text['label-monthly_price']['en-us'] = "Monthly selling price";
$text['label-monthly_price']['ar-eg'] = "";
$text['label-monthly_price']['de-at'] = "Monatlicher Verkaufspreis"; //copied from de-de
$text['label-monthly_price']['de-ch'] = "Monatlicher Verkaufspreis"; //copied from de-de
$text['label-monthly_price']['de-de'] = "Monatlicher Verkaufspreis";
$text['label-monthly_price']['es-cl'] = "Precio mensual de venta";
$text['label-monthly_price']['es-mx'] = "Precio mensual de venta"; //copied from es-cl
$text['label-monthly_price']['fr-ca'] = "Prix mensuel à vendre"; //copied from fr-fr
$text['label-monthly_price']['fr-fr'] = "Prix mensuel à vendre";
$text['label-monthly_price']['he-il'] = "מכירה חודשית";
$text['label-monthly_price']['it-it'] = "Prezzo vendita mensile";
$text['label-monthly_price']['nl-nl'] = "";
$text['label-monthly_price']['pl-pl'] = "Miesięczna cena sprzedaży";
$text['label-monthly_price']['pt-br'] = "Preço mensal de venda";
$text['label-monthly_price']['pt-pt'] = "Preço mensal de venta";
$text['label-monthly_price']['ro-ro'] = "";
$text['label-monthly_price']['ru-ru'] = "Месячный тариф продажи";
$text['label-monthly_price']['sv-se'] = "Säljpris / Månad";
$text['label-monthly_price']['uk-ua'] = "Щомісячна ціна продажу";

$text['label-fax_uuid']['en-us'] = "Fax Detection";
$text['label-fax_uuid']['ar-eg'] = "";
$text['label-fax_uuid']['de-at'] = "Fax Erkennung"; //copied from de-de
$text['label-fax_uuid']['de-ch'] = "Fax Erkennung"; //copied from de-de
$text['label-fax_uuid']['de-de'] = "Fax Erkennung";
$text['label-fax_uuid']['es-cl'] = "Detección de Fax";
$text['label-fax_uuid']['es-mx'] = "Detección de Fax"; //copied from es-cl
$text['label-fax_uuid']['fr-ca'] = "Détection de Fax"; //copied from fr-fr
$text['label-fax_uuid']['fr-fr'] = "Détection de Fax";
$text['label-fax_uuid']['he-il'] = "זיהוי פקסים";
$text['label-fax_uuid']['it-it'] = "Rilevamento Fax";
$text['label-fax_uuid']['nl-nl'] = "";
$text['label-fax_uuid']['pl-pl'] = "Wykrywanie faksu";
$text['label-fax_uuid']['pt-br'] = "Detecção de FAX";
$text['label-fax_uuid']['pt-pt'] = "Detecção de fax";
$text['label-fax_uuid']['ro-ro'] = "";
$text['label-fax_uuid']['ru-ru'] = "Обнаружение факсов";
$text['label-fax_uuid']['sv-se'] = "Fax Detektering";
$text['label-fax_uuid']['uk-ua'] = "Виявлення факсу";

$text['label-domain-name']['en-us'] = "Domain Name";
$text['label-domain-name']['ar-eg'] = "اسم النطاق";
$text['label-domain-name']['de-at'] = "Domänen Name"; //copied from de-de
$text['label-domain-name']['de-ch'] = "Domänen Name"; //copied from de-de
$text['label-domain-name']['de-de'] = "Domänen Name";
$text['label-domain-name']['es-cl'] = "Nombre de Dominio";
$text['label-domain-name']['es-mx'] = "Nombre de Dominio"; //copied from es-cl
$text['label-domain-name']['fr-ca'] = "Nom de Domaine"; //copied from fr-fr
$text['label-domain-name']['fr-fr'] = "Nom de Domaine";
$text['label-domain-name']['he-il'] = "שם דומיין";
$text['label-domain-name']['it-it'] = "Nome Dominio";
$text['label-domain-name']['nl-nl'] = "";
$text['label-domain-name']['pl-pl'] = "Nazwa domeny";
$text['label-domain-name']['pt-br'] = "Nome do Dominio";
$text['label-domain-name']['pt-pt'] = "Nome de Domínio";
$text['label-domain-name']['ro-ro'] = "";
$text['label-domain-name']['ru-ru'] = "Имя Домена";
$text['label-domain-name']['sv-se'] = "Domän Namn";
$text['label-domain-name']['uk-ua'] = "Назва домену";

$text['label-domain']['en-us'] = "域";
$text['label-domain']['ar-eg'] = "Domain";
$text['label-domain']['de-at'] = "Domäne"; //copied from de-de
$text['label-domain']['de-ch'] = "Domäne"; //copied from de-de
$text['label-domain']['de-de'] = "Domäne";
$text['label-domain']['es-cl'] = "Dominio";
$text['label-domain']['es-mx'] = "Dominio"; //copied from es-cl
$text['label-domain']['fr-ca'] = "Domaine"; //copied from fr-fr
$text['label-domain']['fr-fr'] = "Domaine";
$text['label-domain']['he-il'] = "תחום";
$text['label-domain']['it-it'] = "Dominio";
$text['label-domain']['nl-nl'] = "";
$text['label-domain']['pl-pl'] = "Domena";
$text['label-domain']['pt-br'] = "Dominio";
$text['label-domain']['pt-pt'] = "Domínio";
$text['label-domain']['ro-ro'] = "Domeniu";
$text['label-domain']['ru-ru'] = "Домен";
$text['label-domain']['sv-se'] = "Domän";
$text['label-domain']['uk-ua'] = "Домен";

$text['label-detail_action']['en-us'] = "动作";
$text['label-detail_action']['ar-eg'] = "Actions";
$text['label-detail_action']['de-at'] = "Aktionen"; //copied from de-de
$text['label-detail_action']['de-ch'] = "Aktionen"; //copied from de-de
$text['label-detail_action']['de-de'] = "Aktionen";
$text['label-detail_action']['es-cl'] = "Accións";
$text['label-detail_action']['es-mx'] = "Accións"; //copied from es-cl
$text['label-detail_action']['fr-ca'] = "Actions"; //copied from fr-fr
$text['label-detail_action']['fr-fr'] = "Actions";
$text['label-detail_action']['he-il'] = "פעולות";
$text['label-detail_action']['it-it'] = "Azioni";
$text['label-detail_action']['nl-nl'] = "";
$text['label-detail_action']['pl-pl'] = "Operacje (gdzie przesłać rozmowę).";
$text['label-detail_action']['pt-br'] = "Ações"; //copied from pt-pt
$text['label-detail_action']['pt-pt'] = "Ações";
$text['label-detail_action']['ro-ro'] = "";
$text['label-detail_action']['ru-ru'] = "Действия";
$text['label-detail_action']['sv-se'] = "Åtgärder";
$text['label-detail_action']['uk-ua'] = "Дії";

$text['label-city']['en-us'] = "城市";
$text['label-city']['ar-eg'] = "City";
$text['label-city']['de-at'] = ""; //copied from de-de
$text['label-city']['de-ch'] = ""; //copied from de-de
$text['label-city']['de-de'] = "";
$text['label-city']['es-cl'] = "";
$text['label-city']['es-mx'] = ""; //copied from es-cl
$text['label-city']['fr-ca'] = ""; //copied from fr-fr
$text['label-city']['fr-fr'] = "";
$text['label-city']['he-il'] = "";
$text['label-city']['it-it'] = "";
$text['label-city']['nl-nl'] = "";
$text['label-city']['pl-pl'] = "";
$text['label-city']['pt-br'] = ""; //copied from pt-pt
$text['label-city']['pt-pt'] = "";
$text['label-city']['ro-ro'] = "";
$text['label-city']['ru-ru'] = "";
$text['label-city']['sv-se'] = "";
$text['label-city']['uk-ua'] = "";

$text['label-destination_number']['en-us'] = "目的地";
$text['label-destination_number']['ar-eg'] = "Destination";
$text['label-destination_number']['de-at'] = "Ziel"; //copied from de-de
$text['label-destination_number']['de-ch'] = "Ziel"; //copied from de-de
$text['label-destination_number']['de-de'] = "Ziel";
$text['label-destination_number']['es-cl'] = "Destino";
$text['label-destination_number']['es-mx'] = "Destino"; //copied from es-cl
$text['label-destination_number']['fr-ca'] = "Destination"; //copied from fr-fr
$text['label-destination_number']['fr-fr'] = "Destination";
$text['label-destination_number']['he-il'] = "יעד";
$text['label-destination_number']['it-it'] = "Destinazione";
$text['label-destination_number']['nl-nl'] = "";
$text['label-destination_number']['pl-pl'] = "Destynacja";
$text['label-destination_number']['pt-br'] = "Desvio"; //copied from pt-pt
$text['label-destination_number']['pt-pt'] = "Desvio";
$text['label-destination_number']['ro-ro'] = "";
$text['label-destination_number']['ru-ru'] = "Направление";
$text['label-destination_number']['sv-se'] = "Destination";
$text['label-destination_number']['uk-ua'] = "Номер";

$text['label-network_description']['en-us'] = "备注";
$text['label-network_description']['ar-eg'] = "Description";
$text['label-network_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-network_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-network_description']['de-de'] = "Beschreibung";
$text['label-network_description']['es-cl'] = "Descripción";
$text['label-network_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-network_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-network_description']['fr-fr'] = "Description";
$text['label-network_description']['he-il'] = "תאור";
$text['label-network_description']['it-it'] = "Descrizione";
$text['label-network_description']['nl-nl'] = "";
$text['label-network_description']['pl-pl'] = "Opis";
$text['label-network_description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['label-network_description']['pt-pt'] = "Descrição";
$text['label-network_description']['ro-ro'] = "";
$text['label-network_description']['ru-ru'] = "Описание";
$text['label-network_description']['sv-se'] = "Beskrivning";
$text['label-network_description']['uk-ua'] = "Опис";

$text['label-destination_context']['en-us'] = "上下文";
$text['label-destination_context']['ar-eg'] = "Context";
$text['label-destination_context']['de-at'] = "Kontext"; //copied from de-de
$text['label-destination_context']['de-ch'] = "Kontext"; //copied from de-de
$text['label-destination_context']['de-de'] = "Kontext";
$text['label-destination_context']['es-cl'] = "Contexto";
$text['label-destination_context']['es-mx'] = "Contexto"; //copied from es-cl
$text['label-destination_context']['fr-ca'] = "Contexte"; //copied from fr-fr
$text['label-destination_context']['fr-fr'] = "Contexte";
$text['label-destination_context']['he-il'] = "תוכן";
$text['label-destination_context']['it-it'] = "Contesto";
$text['label-destination_context']['nl-nl'] = "";
$text['label-destination_context']['pl-pl'] = "Kontekst";
$text['label-destination_context']['pt-br'] = "Contexto"; //copied from pt-pt
$text['label-destination_context']['pt-pt'] = "Contexto";
$text['label-destination_context']['ro-ro'] = "";
$text['label-destination_context']['ru-ru'] = "Контекст";
$text['label-destination_context']['sv-se'] = "Context";
$text['label-destination_context']['uk-ua'] = "Контекст";

$text['label-destination_cid_name_prefix']['en-us'] = "来电显示名称前缀";
$text['label-destination_cid_name_prefix']['ar-eg'] = "Caller ID Name Prefix";
$text['label-destination_cid_name_prefix']['de-at'] = "Präfix für Anruferkennung (Name)"; //copied from de-de
$text['label-destination_cid_name_prefix']['de-ch'] = "Präfix für Anruferkennung (Name)"; //copied from de-de
$text['label-destination_cid_name_prefix']['de-de'] = "Präfix für Anruferkennung (Name)";
$text['label-destination_cid_name_prefix']['es-cl'] = "Prefijo de Nombre de Caller ID";
$text['label-destination_cid_name_prefix']['es-mx'] = "Prefijo de Nombre de Caller ID"; //copied from es-cl
$text['label-destination_cid_name_prefix']['fr-ca'] = "Préfixe ajouté au nom de l'appelant"; //copied from fr-fr
$text['label-destination_cid_name_prefix']['fr-fr'] = "Préfixe ajouté au nom de l'appelant";
$text['label-destination_cid_name_prefix']['he-il'] = "";
$text['label-destination_cid_name_prefix']['it-it'] = "Prefisso ID Nome Chiamante";
$text['label-destination_cid_name_prefix']['nl-nl'] = "";
$text['label-destination_cid_name_prefix']['pl-pl'] = "Prefiks prezentacji nazwy dzwoniącego";
$text['label-destination_cid_name_prefix']['pt-br'] = "Nome do discador";
$text['label-destination_cid_name_prefix']['pt-pt'] = "Nome do Chamador";
$text['label-destination_cid_name_prefix']['ro-ro'] = "";
$text['label-destination_cid_name_prefix']['ru-ru'] = "Префикс имени (Caller ID) вызывающего абонента";
$text['label-destination_cid_name_prefix']['sv-se'] = "Caller ID Namn Prefix ";
$text['label-destination_cid_name_prefix']['uk-ua'] = "Caller ID Префікс імені";

$text['label-destination_caller_id_number']['en-us'] = "主叫号码";
$text['label-destination_caller_id_number']['ar-eg'] = "Caller ID Number";
$text['label-destination_caller_id_number']['de-at'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['label-destination_caller_id_number']['de-ch'] = "Anruferkennung (Nummer)"; //copied from de-de
$text['label-destination_caller_id_number']['de-de'] = "Anruferkennung (Nummer)";
$text['label-destination_caller_id_number']['es-cl'] = "Número de Caller ID";
$text['label-destination_caller_id_number']['es-mx'] = "Número de Caller ID"; //copied from es-cl
$text['label-destination_caller_id_number']['fr-ca'] = "Caller ID Number"; //copied from fr-fr
$text['label-destination_caller_id_number']['fr-fr'] = "Caller ID Number";
$text['label-destination_caller_id_number']['he-il'] = "";
$text['label-destination_caller_id_number']['it-it'] = "ID Numero Chiamante";
$text['label-destination_caller_id_number']['nl-nl'] = "";
$text['label-destination_caller_id_number']['pl-pl'] = "Prezentaca numeru dzwoniącego";
$text['label-destination_caller_id_number']['pt-br'] = "Número do discador";
$text['label-destination_caller_id_number']['pt-pt'] = "Número do chamador";
$text['label-destination_caller_id_number']['ro-ro'] = "";
$text['label-destination_caller_id_number']['ru-ru'] = "Префикс номера (Caller ID) вызывающего абонента";
$text['label-destination_caller_id_number']['sv-se'] = "Caller ID Nummer";
$text['label-destination_caller_id_number']['uk-ua'] = "Caller ID Номер";

$text['label-destination_caller_id_name']['en-us'] = "主叫名称";
$text['label-destination_caller_id_name']['ar-eg'] = "Caller ID Name";
$text['label-destination_caller_id_name']['de-at'] = "Anruferkennung (Name)"; //copied from de-de
$text['label-destination_caller_id_name']['de-ch'] = "Anruferkennung (Name)"; //copied from de-de
$text['label-destination_caller_id_name']['de-de'] = "Anruferkennung (Name)";
$text['label-destination_caller_id_name']['es-cl'] = "Nombre de Caller ID";
$text['label-destination_caller_id_name']['es-mx'] = "Nombre de Caller ID"; //copied from es-cl
$text['label-destination_caller_id_name']['fr-ca'] = "Caller ID Name"; //copied from fr-fr
$text['label-destination_caller_id_name']['fr-fr'] = "Caller ID Name";
$text['label-destination_caller_id_name']['he-il'] = "";
$text['label-destination_caller_id_name']['it-it'] = "ID Nome Chiamante";
$text['label-destination_caller_id_name']['nl-nl'] = "";
$text['label-destination_caller_id_name']['pl-pl'] = "Prezentaca nazwy dzwoniącego";
$text['label-destination_caller_id_name']['pt-br'] = "Nome do discador";
$text['label-destination_caller_id_name']['pt-pt'] = "Nome do chamador";
$text['label-destination_caller_id_name']['ro-ro'] = "";
$text['label-destination_caller_id_name']['ru-ru'] = "Имя идентификатора (Caller ID) вызывающего абонента";
$text['label-destination_caller_id_name']['sv-se'] = "Caller ID Namn";
$text['label-destination_caller_id_name']['uk-ua'] = "Caller ID Ім’я";

$text['label-carrier']['en-us'] = "Carrier name";
$text['label-carrier']['ar-eg'] = "";
$text['label-carrier']['de-at'] = "Provider Name"; //copied from de-de
$text['label-carrier']['de-ch'] = "Provider Name"; //copied from de-de
$text['label-carrier']['de-de'] = "Provider Name";
$text['label-carrier']['es-cl'] = "Nombre del carrier";
$text['label-carrier']['es-mx'] = "Nombre del carrier"; //copied from es-cl
$text['label-carrier']['fr-ca'] = "Nom du carrier"; //copied from fr-fr
$text['label-carrier']['fr-fr'] = "Nom du carrier";
$text['label-carrier']['he-il'] = "שם מפעיל";
$text['label-carrier']['it-it'] = "Nome Carrier";
$text['label-carrier']['nl-nl'] = "";
$text['label-carrier']['pl-pl'] = "Nazwa operatora";
$text['label-carrier']['pt-br'] = "Nome do transporte";
$text['label-carrier']['pt-pt'] = "Nombre del carrier";
$text['label-carrier']['ro-ro'] = "";
$text['label-carrier']['ru-ru'] = "Название оператора";
$text['label-carrier']['sv-se'] = "Operatör";
$text['label-carrier']['uk-ua'] = "Назва оператора";

$text['label-destination_record']['en-us'] = "Record";
$text['label-destination_record']['ar-eg'] = "";
$text['label-destination_record']['de-at'] = "Aufnehmen"; //copied from de-de
$text['label-destination_record']['de-ch'] = "Aufnehmen"; //copied from de-de
$text['label-destination_record']['de-de'] = "Aufnehmen";
$text['label-destination_record']['es-cl'] = "Grabar";
$text['label-destination_record']['es-mx'] = "Grabar"; //copied from es-cl
$text['label-destination_record']['fr-ca'] = "Enregistrer"; //copied from fr-fr
$text['label-destination_record']['fr-fr'] = "Enregistrer";
$text['label-destination_record']['he-il'] = "";
$text['label-destination_record']['it-it'] = "";
$text['label-destination_record']['nl-nl'] = "";
$text['label-destination_record']['pl-pl'] = "Nagraj";
$text['label-destination_record']['pt-br'] = "Gravar"; //copied from pt-pt
$text['label-destination_record']['pt-pt'] = "Gravar";
$text['label-destination_record']['ro-ro'] = "";
$text['label-destination_record']['ru-ru'] = "Запись";
$text['label-destination_record']['sv-se'] = "Spela In";
$text['label-destination_record']['uk-ua'] = "Запис";

$text['label-account_code']['en-us'] = "Account Code";
$text['label-account_code']['ar-eg'] = "";
$text['label-account_code']['de-at'] = "Kontoschlüssel"; //copied from de-de
$text['label-account_code']['de-ch'] = "Kontoschlüssel"; //copied from de-de
$text['label-account_code']['de-de'] = "Kontoschlüssel";
$text['label-account_code']['es-cl'] = "Código de Cuenta";
$text['label-account_code']['es-mx'] = "Código de Cuenta"; //copied from es-cl
$text['label-account_code']['fr-ca'] = "Code de Compte"; //copied from fr-fr
$text['label-account_code']['fr-fr'] = "Code de Compte";
$text['label-account_code']['he-il'] = "קוד חשבון";
$text['label-account_code']['it-it'] = "Account Code";
$text['label-account_code']['nl-nl'] = "";
$text['label-account_code']['pl-pl'] = "Numer konta bilingowego";
$text['label-account_code']['pt-br'] = "Código da conta";
$text['label-account_code']['pt-pt'] = "Código de Conta";
$text['label-account_code']['ro-ro'] = "";
$text['label-account_code']['ru-ru'] = "Код Учетной Записи";
$text['label-account_code']['sv-se'] = "Account Code";
$text['label-account_code']['uk-ua'] = "Код облікового запису";

$text['header-destinations']['en-us'] = "Destinations";
$text['header-destinations']['ar-eg'] = "جهات الأتصال";
$text['header-destinations']['de-at'] = "Ziele"; //copied from de-de
$text['header-destinations']['de-ch'] = "Ziele"; //copied from de-de
$text['header-destinations']['de-de'] = "Ziele";
$text['header-destinations']['es-cl'] = "Destinos";
$text['header-destinations']['es-mx'] = "Destinos"; //copied from es-cl
$text['header-destinations']['fr-ca'] = "Destinations"; //copied from fr-fr
$text['header-destinations']['fr-fr'] = "Destinations";
$text['header-destinations']['he-il'] = "יעדים";
$text['header-destinations']['it-it'] = "Destinazioni";
$text['header-destinations']['nl-nl'] = "";
$text['header-destinations']['pl-pl'] = "Destynacje";
$text['header-destinations']['pt-br'] = "Destinos"; //copied from pt-pt
$text['header-destinations']['pt-pt'] = "Destinos";
$text['header-destinations']['ro-ro'] = "";
$text['header-destinations']['ru-ru'] = "Направления";
$text['header-destinations']['sv-se'] = "Destinationer";
$text['header-destinations']['uk-ua'] = "Номери";

$text['header-destination-edit']['en-us'] = "Destination";
$text['header-destination-edit']['ar-eg'] = "جهه الأتصال";
$text['header-destination-edit']['de-at'] = "Ziel"; //copied from de-de
$text['header-destination-edit']['de-ch'] = "Ziel"; //copied from de-de
$text['header-destination-edit']['de-de'] = "Ziel";
$text['header-destination-edit']['es-cl'] = "Editar Destino";
$text['header-destination-edit']['es-mx'] = "Editar Destino"; //copied from es-cl
$text['header-destination-edit']['fr-ca'] = "Editer la Destination"; //copied from fr-fr
$text['header-destination-edit']['fr-fr'] = "Editer la Destination";
$text['header-destination-edit']['he-il'] = "יעד";
$text['header-destination-edit']['it-it'] = "Destinazione";
$text['header-destination-edit']['nl-nl'] = "";
$text['header-destination-edit']['pl-pl'] = "Destynacja";
$text['header-destination-edit']['pt-br'] = "Editar destino";
$text['header-destination-edit']['pt-pt'] = "Editar Desvio";
$text['header-destination-edit']['ro-ro'] = "";
$text['header-destination-edit']['ru-ru'] = "Направление";
$text['header-destination-edit']['sv-se'] = "Destination";
$text['header-destination-edit']['uk-ua'] = "Номер";

$text['header-destination-add']['en-us'] = "Destination";
$text['header-destination-add']['ar-eg'] = "جهه الأتصال";
$text['header-destination-add']['de-at'] = "Ziel"; //copied from de-de
$text['header-destination-add']['de-ch'] = "Ziel"; //copied from de-de
$text['header-destination-add']['de-de'] = "Ziel";
$text['header-destination-add']['es-cl'] = "Agregar Destino";
$text['header-destination-add']['es-mx'] = "Agregar Destino"; //copied from es-cl
$text['header-destination-add']['fr-ca'] = "Ajouter une Destination"; //copied from fr-fr
$text['header-destination-add']['fr-fr'] = "Ajouter une Destination";
$text['header-destination-add']['he-il'] = "יעד";
$text['header-destination-add']['it-it'] = "Destinazione";
$text['header-destination-add']['nl-nl'] = "";
$text['header-destination-add']['pl-pl'] = "Destynacja";
$text['header-destination-add']['pt-br'] = "Adicionar desvio";
$text['header-destination-add']['pt-pt'] = "Adicionar Desvio";
$text['header-destination-add']['ro-ro'] = "";
$text['header-destination-add']['ru-ru'] = "Направление";
$text['header-destination-add']['sv-se'] = "Destination";
$text['header-destination-add']['uk-ua'] = "Номер";

$text['header-destination_import']['en-us'] = "Import Destinations";
$text['header-destination_import']['ar-eg'] = "";
$text['header-destination_import']['de-at'] = "Importieren"; //copied from de-de
$text['header-destination_import']['de-ch'] = "Importieren"; //copied from de-de
$text['header-destination_import']['de-de'] = "Importieren";
$text['header-destination_import']['es-cl'] = "Importar";
$text['header-destination_import']['es-mx'] = "Importar"; //copied from es-cl
$text['header-destination_import']['fr-ca'] = "Importe"; //copied from fr-fr
$text['header-destination_import']['fr-fr'] = "Importe";
$text['header-destination_import']['he-il'] = "";
$text['header-destination_import']['it-it'] = "";
$text['header-destination_import']['nl-nl'] = "";
$text['header-destination_import']['pl-pl'] = "Importuj";
$text['header-destination_import']['pt-br'] = "Importar"; //copied from pt-pt
$text['header-destination_import']['pt-pt'] = "Importar";
$text['header-destination_import']['ro-ro'] = "";
$text['header-destination_import']['ru-ru'] = "Импорт";
$text['header-destination_import']['sv-se'] = "Importera";
$text['header-destination_import']['uk-ua'] = "Імпортувати";

$text['description-destination_import']['en-us'] = "Upload delimitted data to add multiple destinations.";
$text['description-destination_import']['ar-eg'] = "";
$text['description-destination_import']['de-at'] = "";
$text['description-destination_import']['de-ch'] = "";
$text['description-destination_import']['de-de'] = "";
$text['description-destination_import']['es-cl'] = "";
$text['description-destination_import']['es-mx'] = "";
$text['description-destination_import']['fr-ca'] = "";
$text['description-destination_import']['fr-fr'] = "";
$text['description-destination_import']['he-il'] = "";
$text['description-destination_import']['it-it'] = "";
$text['description-destination_import']['nl-nl'] = "";
$text['description-destination_import']['pl-pl'] = "";
$text['description-destination_import']['pt-br'] = "";
$text['description-destination_import']['pt-pt'] = "";
$text['description-destination_import']['ro-ro'] = "";
$text['description-destination_import']['ru-ru'] = "";
$text['description-destination_import']['sv-se'] = "";
$text['description-destination_import']['uk-ua'] = "";

$text['description-monthly_price_buy']['en-us'] = "Enter monthly price you pay for this destination (only when inbound)";
$text['description-monthly_price_buy']['ar-eg'] = "";
$text['description-monthly_price_buy']['de-at'] = "Geben Sie den monatlichen Einkaufspreis für dieses Ziel an (nur wenn eingehend)"; //copied from de-de
$text['description-monthly_price_buy']['de-ch'] = "Geben Sie den monatlichen Einkaufspreis für dieses Ziel an (nur wenn eingehend)"; //copied from de-de
$text['description-monthly_price_buy']['de-de'] = "Geben Sie den monatlichen Einkaufspreis für dieses Ziel an (nur wenn eingehend)";
$text['description-monthly_price_buy']['es-cl'] = "Ingrese el precio mensual que usted paga por este destino (sólo entrante)";
$text['description-monthly_price_buy']['es-mx'] = "Ingrese el precio mensual que usted paga por este destino (sólo entrante)"; //copied from es-cl
$text['description-monthly_price_buy']['fr-ca'] = "Entrez prix mensuel de projet de achat pour cette destination (uniquement lorsque entrant)"; //copied from fr-fr
$text['description-monthly_price_buy']['fr-fr'] = "Entrez prix mensuel de projet de achat pour cette destination (uniquement lorsque entrant)";
$text['description-monthly_price_buy']['he-il'] = "";
$text['description-monthly_price_buy']['it-it'] = "Inserire il prezzo mensile pagato per questa destinazione (solo quando in ingresso)";
$text['description-monthly_price_buy']['nl-nl'] = "";
$text['description-monthly_price_buy']['pl-pl'] = "Wpisz kwotę, która ty płacisz miesięcznie za tę destynacje (tylko przychodzące)";
$text['description-monthly_price_buy']['pt-br'] = "Digite o preço mensal para este destino (Apenas quando for entrada)";
$text['description-monthly_price_buy']['pt-pt'] = "Digite o preço mensal de paga para este destino (somente quando entrada)";
$text['description-monthly_price_buy']['ro-ro'] = "";
$text['description-monthly_price_buy']['ru-ru'] = "Введите ежемесячную цену, которую вы платите за это направление (только за входящие)";
$text['description-monthly_price_buy']['sv-se'] = "Ange pris per månad som du betalar för denna destination (endast vid inkommande)";
$text['description-monthly_price_buy']['uk-ua'] = "Введіть щомісячний тариф, який оплачуєте за цей номер (тільки для вхідних)";

$text['description-monthly_price']['en-us'] = "Enter monthly price to bill for this destination (only when inbound)";
$text['description-monthly_price']['ar-eg'] = "";
$text['description-monthly_price']['de-at'] = "Geben Sie den monatlichen Verkaufspreis für dieses Ziel an (nur wenn eingehend)"; //copied from de-de
$text['description-monthly_price']['de-ch'] = "Geben Sie den monatlichen Verkaufspreis für dieses Ziel an (nur wenn eingehend)"; //copied from de-de
$text['description-monthly_price']['de-de'] = "Geben Sie den monatlichen Verkaufspreis für dieses Ziel an (nur wenn eingehend)";
$text['description-monthly_price']['es-cl'] = "Ingrese el precio mensual a cobrar por este destino (sólo entrante)";
$text['description-monthly_price']['es-mx'] = "Ingrese el precio mensual a cobrar por este destino (sólo entrante)"; //copied from es-cl
$text['description-monthly_price']['fr-ca'] = "Entrez prix mensuel de projet de loi pour cette destination (uniquement lorsque entrant)"; //copied from fr-fr
$text['description-monthly_price']['fr-fr'] = "Entrez prix mensuel de projet de loi pour cette destination (uniquement lorsque entrant)";
$text['description-monthly_price']['he-il'] = "";
$text['description-monthly_price']['it-it'] = "Inserire il prezzo mensile da fatturare per questa destinazione (solo quando in ingresso)";
$text['description-monthly_price']['nl-nl'] = "";
$text['description-monthly_price']['pl-pl'] = "Wpisz kwotę, która ty płacisz miesięcznie za tę destynacje (tylko wychodzące)";
$text['description-monthly_price']['pt-br'] = "Digite o preço mensal da conta para este destino";
$text['description-monthly_price']['pt-pt'] = "Digite o preço mensal de conta para este destino (somente quando entrada)";
$text['description-monthly_price']['ro-ro'] = "";
$text['description-monthly_price']['ru-ru'] = "Введите месячную цену для выставления счета для этого пункта назначения (только за входящие)";
$text['description-monthly_price']['sv-se'] = "Ange pris per månad till kund för denna destination (endast vid inkommande)";
$text['description-monthly_price']['uk-ua'] = "Введіть щомісячний тариф для абонентів за цей номер (тільки для вхідних)";

$text['description-fax_uuid']['en-us'] = "Select the fax destination to enable fax detection. ";
$text['description-fax_uuid']['ar-eg'] = "";
$text['description-fax_uuid']['de-at'] = "Wählen Sie einen Fax Server um Faxerkennung für eingehende Anrufe zu aktivieren."; //copied from de-de
$text['description-fax_uuid']['de-ch'] = "Wählen Sie einen Fax Server um Faxerkennung für eingehende Anrufe zu aktivieren."; //copied from de-de
$text['description-fax_uuid']['de-de'] = "Wählen Sie einen Fax Server um Faxerkennung für eingehende Anrufe zu aktivieren.";
$text['description-fax_uuid']['es-cl'] = "Seleccione el destino de fax para activar su detección";
$text['description-fax_uuid']['es-mx'] = "Seleccione el destino de fax para activar su detección"; //copied from es-cl
$text['description-fax_uuid']['fr-ca'] = "Insérer la destination Fax afin d'activer la détection de Fax."; //copied from fr-fr
$text['description-fax_uuid']['fr-fr'] = "Insérer la destination Fax afin d'activer la détection de Fax.";
$text['description-fax_uuid']['he-il'] = "";
$text['description-fax_uuid']['it-it'] = "Seleziona la destinazione fax per abilitare il rilevamento fax.";
$text['description-fax_uuid']['nl-nl'] = "";
$text['description-fax_uuid']['pl-pl'] = "Wybierz destynację faksu aby włączyć wykrywanie faksu.";
$text['description-fax_uuid']['pt-br'] = "Selecione o destino de FAX para ativar a detecção de FAX";
$text['description-fax_uuid']['pt-pt'] = "Seleccione o destino de fax para activar a detecção de fax.";
$text['description-fax_uuid']['ro-ro'] = "";
$text['description-fax_uuid']['ru-ru'] = "Выберите адресат факса, чтобы включить его обнаружение.";
$text['description-fax_uuid']['sv-se'] = "Ange fax destination för att aktivera fax deteketering.";
$text['description-fax_uuid']['uk-ua'] = "Виберіть  номер для факсу, щоб дозволити його виявлення";

$text['description-destination_type']['en-us'] = "选择类型";
$text['description-destination_type']['ar-eg'] = "Select the type.";
$text['description-destination_type']['de-at'] = "Wählen Sie die Art."; //copied from de-de
$text['description-destination_type']['de-ch'] = "Wählen Sie die Art."; //copied from de-de
$text['description-destination_type']['de-de'] = "Wählen Sie die Art.";
$text['description-destination_type']['es-cl'] = "Seleccione el tipo.";
$text['description-destination_type']['es-mx'] = "Seleccione el tipo."; //copied from es-cl
$text['description-destination_type']['fr-ca'] = "Choisir le type."; //copied from fr-fr
$text['description-destination_type']['fr-fr'] = "Choisir le type.";
$text['description-destination_type']['he-il'] = "בחר את הסוג";
$text['description-destination_type']['it-it'] = "Seleziona il tipo.";
$text['description-destination_type']['nl-nl'] = "";
$text['description-destination_type']['pl-pl'] = "Wybierz typ";
$text['description-destination_type']['pt-br'] = "Selecionar o tipo";
$text['description-destination_type']['pt-pt'] = "Seleccionar o tipo.";
$text['description-destination_type']['ro-ro'] = "";
$text['description-destination_type']['ru-ru'] = "Выберите Тип.";
$text['description-destination_type']['sv-se'] = "Välj typ";
$text['description-destination_type']['uk-ua'] = "Виберіть тип";

$text['description-destination_number']['en-us'] = "输入目的地号码";
$text['description-destination_number']['ar-eg'] = "Enter the destination.";
$text['description-destination_number']['de-at'] = "Geben Sie das Ziel an."; //copied from de-de
$text['description-destination_number']['de-ch'] = "Geben Sie das Ziel an."; //copied from de-de
$text['description-destination_number']['de-de'] = "Geben Sie das Ziel an.";
$text['description-destination_number']['es-cl'] = "Ingrese el destino.";
$text['description-destination_number']['es-mx'] = "Ingrese el destino."; //copied from es-cl
$text['description-destination_number']['fr-ca'] = "Indiquer la destination."; //copied from fr-fr
$text['description-destination_number']['fr-fr'] = "Indiquer la destination.";
$text['description-destination_number']['he-il'] = "הכנס יעד";
$text['description-destination_number']['it-it'] = "Inserire la destinazione.";
$text['description-destination_number']['nl-nl'] = "";
$text['description-destination_number']['pl-pl'] = "Wpisz destynację (np. numer DDI).";
$text['description-destination_number']['pt-br'] = "Insira o destino";
$text['description-destination_number']['pt-pt'] = "Introduza o desvio.";
$text['description-destination_number']['ro-ro'] = "";
$text['description-destination_number']['ru-ru'] = "Введите номер назначения.";
$text['description-destination_number']['sv-se'] = "Ange destinationen.";
$text['description-destination_number']['uk-ua'] = "Введіть номер";

$text['description-network_description']['en-us'] = "输入备注";
$text['description-network_description']['ar-eg'] = "Enter a description for this destination (optional).";
$text['description-network_description']['de-at'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional)."; //copied from de-de
$text['description-network_description']['de-ch'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional)."; //copied from de-de
$text['description-network_description']['de-de'] = "Geben Sie eine Beschreibung für dieses Ziel an (optional).";
$text['description-network_description']['es-cl'] = "Ingrese una descripción para este destino (opcional)";
$text['description-network_description']['es-mx'] = "Ingrese una descripción para este destino (opcional)"; //copied from es-cl
$text['description-network_description']['fr-ca'] = "Entrez une description pour cette destination (facultative)."; //copied from fr-fr
$text['description-network_description']['fr-fr'] = "Entrez une description pour cette destination (facultative).";
$text['description-network_description']['he-il'] = "";
$text['description-network_description']['it-it'] = "Inserire una descrizione per questa destinazione (opzionale).";
$text['description-network_description']['nl-nl'] = "";
$text['description-network_description']['pl-pl'] = "Wpisz opis tej destynacji (opcjonalne)";
$text['description-network_description']['pt-br'] = "Insira uma descrição para este destino (opcional)";
$text['description-network_description']['pt-pt'] = "Introduza uma descrição para este destino (opcional).";
$text['description-network_description']['ro-ro'] = "";
$text['description-network_description']['ru-ru'] = "Введите описание для этого места назначения (опционально).";
$text['description-network_description']['sv-se'] = "Ange en beskrivning för denna destination (frivillig).";
$text['description-network_description']['uk-ua'] = "Введіть опис для номера (не обов’язково)";

$text['description-destination_context']['en-us'] = "输入上下午";
$text['description-destination_context']['ar-eg'] = "Enter the context.";
$text['description-destination_context']['de-at'] = "Geben Sie den Kontext an."; //copied from de-de
$text['description-destination_context']['de-ch'] = "Geben Sie den Kontext an."; //copied from de-de
$text['description-destination_context']['de-de'] = "Geben Sie den Kontext an.";
$text['description-destination_context']['es-cl'] = "Ingrese el contexto";
$text['description-destination_context']['es-mx'] = "Ingrese el contexto"; //copied from es-cl
$text['description-destination_context']['fr-ca'] = "Entrer le context."; //copied from fr-fr
$text['description-destination_context']['fr-fr'] = "Entrer le context.";
$text['description-destination_context']['he-il'] = "";
$text['description-destination_context']['it-it'] = "Inserire il contesto.";
$text['description-destination_context']['nl-nl'] = "";
$text['description-destination_context']['pl-pl'] = "Wpisz kontekst";
$text['description-destination_context']['pt-br'] = "Insira o contexto";
$text['description-destination_context']['pt-pt'] = "Introduza o contexto.";
$text['description-destination_context']['ro-ro'] = "";
$text['description-destination_context']['ru-ru'] = "Введите контекст.";
$text['description-destination_context']['sv-se'] = "Ange Context.";
$text['description-destination_context']['uk-ua'] = "Контекст";

$text['description-destination_cid_name_prefix']['en-us'] = "为来电显示名称(主叫名称)设置前缀";
$text['description-destination_cid_name_prefix']['ar-eg'] = "Set a prefix on the caller ID name.";
$text['description-destination_cid_name_prefix']['de-at'] = "Geben Sie ein Präfix für die Anruferkennung (Name) an."; //copied from de-de
$text['description-destination_cid_name_prefix']['de-ch'] = "Geben Sie ein Präfix für die Anruferkennung (Name) an."; //copied from de-de
$text['description-destination_cid_name_prefix']['de-de'] = "Geben Sie ein Präfix für die Anruferkennung (Name) an.";
$text['description-destination_cid_name_prefix']['es-cl'] = "Configurar el prefijo del nombre de Caller ID.";
$text['description-destination_cid_name_prefix']['es-mx'] = "Configurar el prefijo del nombre de Caller ID."; //copied from es-cl
$text['description-destination_cid_name_prefix']['fr-ca'] = "Choisir un préfixe à ajouter au nom de l'appelant."; //copied from fr-fr
$text['description-destination_cid_name_prefix']['fr-fr'] = "Choisir un préfixe à ajouter au nom de l'appelant.";
$text['description-destination_cid_name_prefix']['he-il'] = "";
$text['description-destination_cid_name_prefix']['it-it'] = "Imposta un prefisso sul Nome Chiamante.";
$text['description-destination_cid_name_prefix']['nl-nl'] = "";
$text['description-destination_cid_name_prefix']['pl-pl'] = "Ustaw prefiks prezentacji nazwy dzwoniącego";
$text['description-destination_cid_name_prefix']['pt-br'] = "Escolha um prefixo e adicione ao nome do discador ";
$text['description-destination_cid_name_prefix']['pt-pt'] = "Escolha um prefixo a adicionar ao nome do chamador.";
$text['description-destination_cid_name_prefix']['ro-ro'] = "";
$text['description-destination_cid_name_prefix']['ru-ru'] = "Задайте префикс имени (caller ID) идентификатора вызывающего абонента.";
$text['description-destination_cid_name_prefix']['sv-se'] = "Ange ett prefix för Caller ID Namn.";
$text['description-destination_cid_name_prefix']['uk-ua'] = "Введіть префікс для імені Caller ID";

$text['description-destination_caller_id_number']['en-us'] = "输入主叫号码";
$text['description-destination_caller_id_number']['ar-eg'] = "Enter the caller ID number.";
$text['description-destination_caller_id_number']['de-at'] = "Geben Sie die Anruferkennung (Nummer) an."; //copied from de-de
$text['description-destination_caller_id_number']['de-ch'] = "Geben Sie die Anruferkennung (Nummer) an."; //copied from de-de
$text['description-destination_caller_id_number']['de-de'] = "Geben Sie die Anruferkennung (Nummer) an.";
$text['description-destination_caller_id_number']['es-cl'] = "Ingrese el número de Caller ID";
$text['description-destination_caller_id_number']['es-mx'] = "Ingrese el número de Caller ID"; //copied from es-cl
$text['description-destination_caller_id_number']['fr-ca'] = "Insérer le numéro d'appelant."; //copied from fr-fr
$text['description-destination_caller_id_number']['fr-fr'] = "Insérer le numéro d'appelant.";
$text['description-destination_caller_id_number']['he-il'] = "";
$text['description-destination_caller_id_number']['it-it'] = "Inserire il Numero Chiamante.";
$text['description-destination_caller_id_number']['nl-nl'] = "";
$text['description-destination_caller_id_number']['pl-pl'] = "Wpisz prezentację numeru dzwoniącego";
$text['description-destination_caller_id_number']['pt-br'] = "Insira o número do discador";
$text['description-destination_caller_id_number']['pt-pt'] = "Introduza o número do chamador";
$text['description-destination_caller_id_number']['ro-ro'] = "";
$text['description-destination_caller_id_number']['ru-ru'] = "Введите идентификационный номер (caller ID) вызывающего абонента.";
$text['description-destination_caller_id_number']['sv-se'] = "Ange Caller ID Nummer.";
$text['description-destination_caller_id_number']['uk-ua'] = "Введіть номер Caller ID";

$text['description-destination_caller_id_name']['en-us'] = "输入主叫名称";
$text['description-destination_caller_id_name']['ar-eg'] = "Enter the caller ID name.";
$text['description-destination_caller_id_name']['de-at'] = "Geben Sie die Anruferkennung (Name) an."; //copied from de-de
$text['description-destination_caller_id_name']['de-ch'] = "Geben Sie die Anruferkennung (Name) an."; //copied from de-de
$text['description-destination_caller_id_name']['de-de'] = "Geben Sie die Anruferkennung (Name) an.";
$text['description-destination_caller_id_name']['es-cl'] = "Ingrese el nombre de caller ID";
$text['description-destination_caller_id_name']['es-mx'] = "Ingrese el nombre de caller ID"; //copied from es-cl
$text['description-destination_caller_id_name']['fr-ca'] = "Insérer le nom d'appelant."; //copied from fr-fr
$text['description-destination_caller_id_name']['fr-fr'] = "Insérer le nom d'appelant.";
$text['description-destination_caller_id_name']['he-il'] = "";
$text['description-destination_caller_id_name']['it-it'] = "Inserire Il Nome Chiamante.";
$text['description-destination_caller_id_name']['nl-nl'] = "";
$text['description-destination_caller_id_name']['pl-pl'] = "Wpisz prezentację nazwy dzwoniącego";
$text['description-destination_caller_id_name']['pt-br'] = "Insira o nome do discador";
$text['description-destination_caller_id_name']['pt-pt'] = "Introduza o nome do chamador";
$text['description-destination_caller_id_name']['ro-ro'] = "";
$text['description-destination_caller_id_name']['ru-ru'] = "Введите имя (caller ID) вызывающего абонента.";
$text['description-destination_caller_id_name']['sv-se'] = "Ange Caller ID Namn.";
$text['description-destination_caller_id_name']['uk-ua'] = "Введіть ім’я  Caller ID";

$text['description-carrier']['en-us'] = "Enter the carrier name. This is use to keep track incase billing";
$text['description-carrier']['ar-eg'] = "";
$text['description-carrier']['de-at'] = "Geben Sie den Providernamen an. Dies wird für das Abrechnungsmodul verwendet."; //copied from de-de
$text['description-carrier']['de-ch'] = "Geben Sie den Providernamen an. Dies wird für das Abrechnungsmodul verwendet."; //copied from de-de
$text['description-carrier']['de-de'] = "Geben Sie den Providernamen an. Dies wird für das Abrechnungsmodul verwendet.";
$text['description-carrier']['es-cl'] = "Introduzca el nombre del carrier. Esto se utiliza para realizar un seguimiento en caso de facturación";
$text['description-carrier']['es-mx'] = "Introduzca el nombre del carrier. Esto se utiliza para realizar un seguimiento en caso de facturación"; //copied from es-cl
$text['description-carrier']['fr-ca'] = "Entrez le nom du transporteur. Ceci est utilise pour garder une trace encas facturation"; //copied from fr-fr
$text['description-carrier']['fr-fr'] = "Entrez le nom du transporteur. Ceci est utilise pour garder une trace encas facturation";
$text['description-carrier']['he-il'] = "";
$text['description-carrier']['it-it'] = "Inserire il nome del carrier. Viene usato per tenre traccia della fatturazione.";
$text['description-carrier']['nl-nl'] = "";
$text['description-carrier']['pl-pl'] = "Wpisz nazwę operatora. Może ona być pomocna przy rozliczeniach";
$text['description-carrier']['pt-br'] = "Digite o nome da operadora. Isto é usado para manter o controle sobre o faturamento";
$text['description-carrier']['pt-pt'] = "Digite o nome da operadora. Isto é usado para manter o controle meter faturamento";
$text['description-carrier']['ro-ro'] = "";
$text['description-carrier']['ru-ru'] = "Введите имя оператора. Это используется для тарификации";
$text['description-carrier']['sv-se'] = "Ange operatörens namn. Detta används för att hålla reda på debitering.";
$text['description-carrier']['uk-ua'] = "Введіть назву оператора. Використовується для тарифікації";

$text['description-area_code']['en-us'] = "输入区域码，区域码为身份证号码前4位，如湖南省长沙市的区域码为：4301";
$text['description-area_code']['ar-eg'] = "";
$text['description-area_code']['de-at'] = "";
$text['description-area_code']['de-ch'] = "";
$text['description-area_code']['de-de'] = "";
$text['description-area_code']['es-cl'] = "";
$text['description-area_code']['es-mx'] = "";
$text['description-area_code']['fr-ca'] = "";
$text['description-area_code']['fr-fr'] = "";
$text['description-area_code']['he-il'] = "";
$text['description-area_code']['it-it'] = "";
$text['description-area_code']['nl-nl'] = "";
$text['description-area_code']['pl-pl'] = "";
$text['description-area_code']['pt-br'] = "";
$text['description-area_code']['pt-pt'] = "";
$text['description-area_code']['ro-ro'] = "";
$text['description-area_code']['ru-ru'] = "";
$text['description-area_code']['sv-se'] = "";
$text['description-area_code']['uk-ua'] = "";

$text['description-readonly']['en-us'] = "（只读）";
$text['description-readonly']['ar-eg'] = "readonly";
$text['description-readonly']['de-at'] = "readonly";
$text['description-readonly']['de-ch'] = "readonly";
$text['description-readonly']['de-de'] = "readonly";
$text['description-readonly']['es-cl'] = "readonly";
$text['description-readonly']['es-mx'] = "readonly";
$text['description-readonly']['fr-ca'] = "readonly";
$text['description-readonly']['fr-fr'] = "readonly";
$text['description-readonly']['he-il'] = "readonly";
$text['description-readonly']['it-it'] = "readonly";
$text['description-readonly']['nl-nl'] = "readonly";
$text['description-readonly']['pl-pl'] = "readonly";
$text['description-readonly']['pt-br'] = "readonly";
$text['description-readonly']['pt-pt'] = "readonly";
$text['description-readonly']['ro-ro'] = "readonly";
$text['description-readonly']['ru-ru'] = "readonly";
$text['description-readonly']['sv-se'] = "readonly";
$text['description-readonly']['uk-ua'] = "readonly";

$text['billing-warning']['en-us'] = "If you are using fusionpbx billing application, make sure to add accountcode and carrier variables.";
$text['billing-warning']['ar-eg'] = "";
$text['billing-warning']['de-at'] = "Wenn Sie die Fusionpbx Abrechnung verwenden, stellen Sie sicher, dass Account-Code und Betreiber-Variablen gesetzt sind."; //copied from de-de
$text['billing-warning']['de-ch'] = "Wenn Sie die Fusionpbx Abrechnung verwenden, stellen Sie sicher, dass Account-Code und Betreiber-Variablen gesetzt sind."; //copied from de-de
$text['billing-warning']['de-de'] = "Wenn Sie die Fusionpbx Abrechnung verwenden, stellen Sie sicher, dass Account-Code und Betreiber-Variablen gesetzt sind.";
$text['billing-warning']['es-cl'] = "Si está utilizando la aplicación de facturación fusionpbx, asegúrese de agregar lasvariables accountcode y carrier";
$text['billing-warning']['es-mx'] = "Si está utilizando la aplicación de facturación fusionpbx, asegúrese de agregar lasvariables accountcode y carrier"; //copied from es-cl
$text['billing-warning']['fr-ca'] = "Si vous utilisez l'application de facturation fusionpbx, assurez-vous d'ajouter des variables de accountcode et carrier"; //copied from fr-fr
$text['billing-warning']['fr-fr'] = "Si vous utilisez l'application de facturation fusionpbx, assurez-vous d'ajouter des variables de accountcode et carrier";
$text['billing-warning']['he-il'] = "";
$text['billing-warning']['it-it'] = "Se si usa l'applicazione per la fatturazione di fusionpbx, accertarsi di valorizzare accountcode e carrier.";
$text['billing-warning']['nl-nl'] = "";
$text['billing-warning']['pl-pl'] = "Jeżeli używasz platformę billingowa z Fusionpbx, dodaj numer konta billingowego oraz zmienne operatora";
$text['billing-warning']['pt-br'] = "Se você estiver usando o aplicativo de faturamento, certifique-se em adicionar as variáveis de transporte";
$text['billing-warning']['pt-pt'] = "Se você estiver usando o aplicativo de faturamento fusionpbx, certifique-se de adicionar variáveis accountcode e carrier";
$text['billing-warning']['ro-ro'] = "";
$text['billing-warning']['ru-ru'] = "Если вы используете приложение биллинга FusionPBX, обязательно добавьте код учетной записи и переменные-несущие.";
$text['billing-warning']['sv-se'] = "Om du använder fusionpbx fakturering program, se till att lägga till 'account code' och operatör variabler";
$text['billing-warning']['uk-ua'] = "Якщо ви користуєтеся додатком для тарифікації в fusionpbx, то переконайтеся, щоб додано змінні код облікового запису і оператора. ";

?>
